### ISSUE TITLE
Formula Exports prepends "@" to Add In Function

### ISSUE THREAD

**Issue by ianalderman** [dfinke/ImportExcel#1154]
Hi Thank you for the amazing module!  I have become unstuck on my final challenge:

If I set Cell Value to a formula that uses an Add-In similar to: 

"=IA.MYFUNCTION(param,param)" 

when I open the workbook in Excel it is output as: 

=@IA.MYFUNCTION(param,param) 

Excel just gives me a #NAME error a this point.  Any thoughts on what I am doing wrong?

I had a read of #1109 and #1105 but wasn't able to find a solution from those.

Thanks again!

**Comment by dfinke** [comment]
Please post a way to repro this, including the PS and xlsx

**Comment by MartinParis** [comment]
This does the trick for me, also creates a @ before the function, XLOOKUP in my case.
Code in Powershell.
`$excelPackage.Workbook.Worksheets['Sheet1'].Cells['AD2'].Formula = "=XLOOKUP(O2,SNGData[Config Id],SNGData[Block],""_Not Found"",0,1)"`
Excel content in sheet: `"=@XLOOKUP(O2,SNGData[Config Id],SNGData[Email],"_Not Found",0,1)"`

If I set this value as a string (.Value) it does not add the @ character, but it also not a formula. Once entered It becomes a formula.

PowerShell 7.2.2
ImportExcel/7.3.0

**Comment by MartinParis** [comment]
Hmm, might be just my Excel version acting up...
https://support.microsoft.com/en-us/office/implicit-intersection-operator-ce3be07b-0101-4450-a24e-c1c999be2b34?ui=en-us&rs=en-us&ad=us

Running on Mac, V16.60 (22041000)

But would be nice if it did not happen.

**Comment by dfinke** [comment]
Please post a way to repro this, including the PS and xlsx

**Comment by MartinParis** [comment]
Example with xlsx before and after.
ps1 extension not allowed to upload, added .txt as suffix.
[test1.xlsx](https://github.com/dfinke/ImportExcel/files/8575431/test1.xlsx)
[test1_after.xlsx](https://github.com/dfinke/ImportExcel/files/8575432/test1_after.xlsx)
[Reproduce_#1154.ps1.txt](https://github.com/dfinke/ImportExcel/files/8575436/Reproduce_.1154.ps1.txt).

**Comment by dfinke** [comment]
is `XLOOKUP` the new function for O365? I don't have that function in my Excel, run it locally. When I run the script it does not add the `@`.

**Comment by stahler** [comment]
Yes, it is a new function (a great one!).
_"Excel for Microsoft 365 Excel for Microsoft 365 for Mac Excel for the web Excel 2021 Excel 2021 for Mac Excel for iPad Excel for iPhone Excel for Android tablets Excel for Android phones"_
https://support.microsoft.com/en-us/office/xlookup-function-b7fd680e-6d10-43e6-84f9-88eae8bf5929

**Comment by MartinParis** [comment]
I was afraid of that, might be another new thing from Excel.
Xlookup is a much needed improvement on vlookup.
https://support.microsoft.com/en-us/office/xlookup-function-b7fd680e-6d10-43e6-84f9-88eae8bf5929

They keep on going...
https://techcommunity.microsoft.com/t5/excel-blog/announcing-new-text-and-array-functions/ba-p/3186066

**Comment by MartinParis** [comment]
I will try this later, maybe that will prevent the intersection addition.

If you remove an automatically added @ and later open the workbook in an older version of Excel, it will appear as a [legacy array formula](https://support.microsoft.com/en-us/office/dynamic-array-formulas-vs-legacy-cse-array-formulas-ca421f1b-fbb2-4c99-9924-df571bd4f1b4) (wrapped with braces {}), this is done to ensure the older version will not trigger implicit intersection.

**Comment by MartinParis** [comment]
Hmm, this breaks the Excel file. It then tries to repair the file, contents of that cell is gone.
Added three to D6 first, saved without values in E column.
$excelPackage.Workbook.Worksheets['Sheet1'].Cells['E6'].Value = '={XLOOKUP(D6,Count[CountString],Count[CountNumber],"Not Found",0,1)}'

**Comment by MartinParis** [comment]
Oh, typo in previous remark, the opening curly bracket needs to go before the = sign.
Breaks the Excel file in the same way though.

**Comment by MartinParis** [comment]
Another angle tried, what if I add the formula already in the original data (coming from powershell object).
Using your MultipleTables example code, added the formula as data.
Region,Area,Product,Units,Cost,Appletest
North,A1,Apple,100,.5,"=XLOOKUP(""Apple"",C2:C7,E2:E7,""Not found"",0,1)"

Still gives the @ in front of the Xlookup.

**Comment by dfinke** [comment]
@phillipsmikealan Is this in O365? If not please could you post a small repro. I could not repro it with the `XLOOKUP`

**Comment by phillipsmikealan** [comment]
@dfinke It's in Excel Microsoft 365; the desktop version...

I'll see if I can strip the file of it's data on Monday. It contains a ton of sensitive info, so it will be a chore. But I ran some commands to see the cell when the formula is in correctly and it says it's an Array Formula. Wondering if that means we have to set it with Set-ExcelRange?

**Comment by dfinke** [comment]
Be great if you could check with `Set-ExcelRange`, though it that should use the same code path for setting formulas, I'd need to check. Optimally, this should work, so I need to determine the root cause.

**Comment by MartinParis** [comment]
@phillipsmikealan Hi, not to harass you, but were you able to verify with the `Set-ExcelRange`?
My skill level is too low to do ut myself :-(.
And I really start to dislike those pesky @ in my formulas.

**Comment by MartinParis** [comment]
Succes! I have succeeded to prevent Excel from adding the @ to the formula when it opens the file.
I started with an Excel file which already has an XLOOKUP formula in it, this is in the xml:
`<c r="D2" s="0" t="str"><f>_xlfn.XLOOKUP(D1,Table1[a],Table1[b],"Not Found",0,1)</f><v>w</v></c>`
Then using ImportExcel I added the same formula in code with the string that I see in the Excel UI in the cell mentioned above:
`=XLOOKUP(D1,Table1[a],Table1[b],"Not Found",0,1)` in the cell below it.

So when checking the xml I saw the difference in the prefix, "=" when added in code, and "_xlfn." in Excel itself.
There is not much data on this, but this article describes what it is used for: 
https://support.microsoft.com/en-us/office/issue-an-xlfn-prefix-is-displayed-in-front-of-a-formula-882f1ef7-68fb-4fcd-8d54-9fbb77fd5025

So, if I would add that prefix to the Formula in code instead of "="?
And, yes that worked, when opening the file Excel recognises it and does not prefix it with @.
It does need to be added as .Formula, with .Value is the actual value that is used by Excel as a Value.

So this works for me.
`$excelPackage.Workbook.Worksheets['Sheet1'].Cells['AD2'].Formula = "_xlfn.XLOOKUP(O2,SNGData[Config Id],SNGData[Block],""_Not Found"",0,1)"`

There is one remaining "issue" for me, I would expect the Formula to be repeated, as it is in a cell belonging to a table.
It does not do that when opening the file though, only when entering in the UI.
But luckily another user already solved that here: https://github.com/dfinke/ImportExcel/issues/1175
Thank you @Gtoml!
I just have to write the formulas (in 4 columns) about x times as reported in the $range: A1:AE157481 for the table I am currently using for testing.
Which just takes under 4 seconds, so that is do-able.

And since it cannot be said enough, BIG thanks for @dfinke to have made this module!

**Comment by MartinParis** [comment]
Yes, that will be fun to do. But I am also generation some other Excel files and there a formula is still looking like this, the @ is added as a prefix to a column, regardless of using `_xlfn.` prefix.
Let me see if that can be resolved as well.
`=IF(Delta7!A2="No Delta",0,COUNTA(UNIQUE(ChangedEffectPolicies[@assignmentName]&ChangedEffectPolicies[@assignmentScope]&ChangedEffectPolicies[@policyName])))`
As mentioned in #1183.

**Comment by MartinParis** [comment]
Ah, ok, it is about how Excel interprets the formula when opening the file, there is a tag "t" (type?) that is either "e" or "array".
When it is "e" Excel adds the @ to make sure nothing breaks, but it actually does.
This happens when the formula is added without the `_xlfn.` prefix.
In this case it is not the IF itself that triggers this, but the UNIQUE. So it is solved when prefixing UNIQUE with the `_xlfn.` prefix.
Funny enough the saved formula is also saved without the "=" prefix before the IF :-).
`<c r="A14" cm="1"><f t="array" ref="A14">IF(Delta7!A2="No Delta",0,COUNTA(_xlfn.UNIQUE(ChangedEffectPolicies[assignmentName]&amp;ChangedEffectPolicies[assignmentScope]&amp;ChangedEffectPolicies[policyName])))</f><v>2</v></c>`. There is no difference if the Formula is added with or without the "=" prefix when opening the file.

I'll do a more generic FAQ writeup for the @ challenge, tomorrow or in the weekend.

**Comment by MartinParis** [comment]
Cool, one added benefit of prefixing with `_xlfn.` is that the calculation is done when opening the sheet.
A UNIQUE formula will not do that if not prefixed.
The -Calculate option does not make a difference, now saving without it, the prefix triggers the calculate.
