### ISSUE TITLE
Consider publishing module to Chocolatey

### ISSUE THREAD

**Issue by dfinke** [dfinke/ImportExcel#1287]
Setup the needed infrastructure to package and publish ImportExcel to Chocolatey

**Comment by teknowledgist** [comment]
Hi!  Excel-lent module!  😄 

OK if I help out here?  https://community.chocolatey.org/packages/importexcel.powershell

I've made it automatic, so it should also be easy to update.  It's not approved yet, so if you object or want me to change anything, I can easily do that or even just recall it.   I will hand over or share the reigns at any point if you want.

**Comment by dfinke** [comment]
I will take a look. Thanks! I may want to automate it from GitHub Actions. I publish to the PS Gallery from my local machine with a script. If this makes sense, be good for me to have a script so I can publish to both when I push another release.

Thanks again!

**Comment by dfinke** [comment]
@teknowledgist any news on this? After thinking about it, I think I'd prefer if only I had access to release it so I can comfortably say it is the official release. - Thanks for working on this

**Comment by teknowledgist** [comment]
@dfinke The package has been submitted for moderation and passed the automated tests:

https://community.chocolatey.org/packages/importexcel.powershell#versionhistory

All it is waiting for now is one of the moderators to review the code and approve it.  My source code for the Chocolatey package is here:

https://github.com/teknowledgist/Chocolatey-packages/tree/master/automatic/importexcel.powershell

As the author, you can contact the Chocolatey Community repository admins to be given maintainership at any time.  That said, I'm happy to add you as a maintainer if you have a Chocolatey Community repository account.  At that point, you could remove me as a maintainer if you choose.  Either way, you might want to contact the admins anyway because I believe they have some kind of flag for author-maintained packages to skip the manual moderation process and get the latest versions up faster.  

Let me know if there is anything I can do to assist.

**Comment by dfinke** [comment]
Thanks for the update! I will check it out
