### ISSUE TITLE
Spill formulas not being retained when updating workbook

### ISSUE THREAD

**Issue by MarkJEverest** [dfinke/ImportExcel#1302]
Hi,

I have an Excel workbook with some spill formulas in but when opening the file with "Open-ExcelPackage" and then closing it again, the formulas are surrounded by curly braces and therefore do not work when the file is opened in Excel.
How can I edit the file and retain these values?

I've created a sample file. The tab Data has a data table and the Stuff tab has a spill formula.

Here is the spill formula before using "Open-ExcelPackage":
![image](https://user-images.githubusercontent.com/20557892/200275953-5616928b-a8ae-4991-9647-ba270c4a518e.png)

... and here is the same view after using "Open-ExcelPackage" and "Close-ExcelPackage":
![image](https://user-images.githubusercontent.com/20557892/200276127-a553108e-7e6b-4698-af0a-200d58b403c7.png)

As you can see the formula is surrounded by braces and no longer works as a spill formula, so adding new rows to the data table is not reflected in the "stuff" tab (in fact one is, but no others are)

**Comment by MarkJEverest** [comment]
[Book1.xlsx](https://github.com/dfinke/ImportExcel/files/9950119/Book1.xlsx)
Here is the sample file

**Comment by dfinke** [comment]
Do you only do `Open-ExcelPackage` and `Close-ExcelPackage` and that changes?

**Comment by MarkJEverest** [comment]
Yes that is all that is needed to cause the issue

**Comment by MarkJEverest** [comment]
Any update on this issue?

**Comment by dfinke** [comment]
No update.
I see this in the cell. Did you create the xlsx with ImportExcel? 
The `_xlfn_...` is something that is done for certain things.

![image](https://user-images.githubusercontent.com/67258/209441964-27cb018f-d752-43a9-ab7a-3ed045ec8293.png)

**Comment by MarkJEverest** [comment]
No, the workbook was initially made with Excel.

**Comment by MarkJEverest** [comment]
Post to unstale

**Comment by MarkJEverest** [comment]
Is this fixed then?

**Comment by dfinke** [comment]
No, not going to be able to look at it for now. It's in the backlog. If more folks have the issue, I can bump the priority.

**Comment by MarkJEverest** [comment]
👍

**Comment by clienart-bmx** [comment]
Hello,
I have the same issue with cells containing INDIRECT and TEXTSPLIT functions.
For the INDIRECT cells, the automatic addition of curly braces has no effect, but for the TEXTSPLIT cells, it prevents spilling to adjacent cells and since I use this formula to perform data validation in another cell (and show a dropdown of possible values), it only shows the first choice in the dropdown instead of all choices (the other choices would have spilled in adjacent cells to the right of the cell with the TEXTSPLIT formula.

I believe Excel 365 automatically adds curly braces (array formula) to formulas that are not supported by the current version of Excel. Since TEXTSPLIT is a new Excel 365 formula and the server where I use ImportExcel doesn't have Excel installed, I believe this is why the curly braces are automatically added when I re-open the workbook...

**Comment by geoced** [comment]
It looks like it's not linked to new formulas either, as I was able to reproduce the error by replacing the new TEXTSPLIT formula with the legacy FILTERXML formula.

I have attached an example Excel file. If you open it in Excel, both versions of the formula result in a spill over. And this is the real issue here. It looks like ImportExcel doesn't support spill over. If you use Open-ExcelPackage and immediately Close-ExcelPackage on this example file, then open it with Excel, you will see that the formulas have been changed to array formulas.

EPPlus 7 added support for dynamic arrays and spill over, as explained here: https://www.epplussoftware.com/en/Developers/EPPlus7.
Which version of EPP does ImportExcel use ?

**Comment by dfinke** [comment]
ImportExcel uses the free version of EPPlus, 4.5. Sounds like they fixed it moving forward. I don't have any plans to migrate to the latest EPPlus tho

**Comment by geoced** [comment]
That's too bad, especially since I cannot find a reliable workaround to create a dynamic data validation list.

I've tried to remove the array formula and recreate the spillover formula by editing the spreadsheet as a `ComObject`: it works but it requires Excel installed on the server, which is a no go.

I've also tried to switch to transform the dynamic spillover `TEXTSPLIT `formula into a static list of cells, each `INDEX`ing into the `TEXTSPLIT `array, and then changing the data validation list source from `=SpillOverCell#` to `=OFFSET(INDEX(INDIRECT("SpillOverCell"), 1), 0, 0, 1, COUNT(IF(INDIRECT("SpillOverCell")="", "", 1)))` (which essentially removes blank cells in the static range), but for some reasons, every time I close and reopen the file, the dropdown list only shows the first cell in the static range. If I open the data validation window in Excel and click OK without changing anything, it works again. Until I close the file. Frustrating !!!

I might consider macros, but I'm not sure if ImportExcel can work with XLSM files. And macros are usually frowned upon at my job...

**Comment by Emilius256** [comment]
Hello, I have the same problem with my excel file, a formula is "converted" to an array when using `Open-ExcelPackage` and `Close-ExcelPackage`.
Did someone found a workaround?
Many thanks

**Comment by geoced** [comment]
I ended up creating a macro to fix the broken formula automatically when the workbook opens. Not ideal, but that's the only reliable solution I could find.

**Comment by Emilius256** [comment]
> I ended up creating a macro to fix the broken formula automatically when the workbook opens. Not ideal, but that's the only reliable solution I could find.

Do you have an example of the macro?
I do not know where to start

**Comment by geoced** [comment]
Here is what I did, you will need to rename "Helper" & "IpAddressesDropdownList" according to your own workbook  :
```
# ImportExcel automatically transforms spillover dynamic arrays into CSE array formulas, breaking data validation dropdown lists.
# Using the legacy method of editing an Excel file with a ComObject, to remove the array formula and replace it with a spillover formula would be a solution,
# but it requires Excel to be installed on the server.
# Instead, create a VBA macro that will run when the workbook opens and replaces the broken array formulas with the initial spillover formulas.
# The array formula must be cleared before applying the spillover formula, otherwise you get a "You can't change part of an array" error.

$thisWorkbookMacro = @'
Private Sub Workbook_Open()
    On Error Resume Next
    Sheets("Helper").Range("IpAddressesDropdownList").CurrentArray.ClearContents
    Sheets("Helper").Range("IpAddressesDropdownList").Formula2 = "original spillover formula"
End Sub
'@

$reportFilePathWithMacros = $reportFilePath -replace '\.xlsx$', '.xlsm'
Move-Item -Path $reportFilePath -Destination $reportFilePathWithMacros
$xl = Open-ExcelPackage -Path $reportFilePathWithMacros
$wb = $xl.Workbook
$wb.CreateVBAProject()
($wb.VbaProject.Modules | Where-Object Name -EQ 'ThisWorkbook').Code = $thisWorkbookMacro
Close-ExcelPackage -ExcelPackage $xl
```

**Comment by Emilius256** [comment]
> Here is what I did, you will need to rename "Helper" & "IpAddressesDropdownList" according to your own workbook :
> 
> ```
> # ImportExcel automatically transforms spillover dynamic arrays into CSE array formulas, breaking data validation dropdown lists.
> # Using the legacy method of editing an Excel file with a ComObject, to remove the array formula and replace it with a spillover formula would be a solution,
> # but it requires Excel to be installed on the server.
> # Instead, create a VBA macro that will run when the workbook opens and replaces the broken array formulas with the initial spillover formulas.
> # The array formula must be cleared before applying the spillover formula, otherwise you get a "You can't change part of an array" error.
> 
> $thisWorkbookMacro = @'
> Private Sub Workbook_Open()
>     On Error Resume Next
>     Sheets("Helper").Range("IpAddressesDropdownList").CurrentArray.ClearContents
>     Sheets("Helper").Range("IpAddressesDropdownList").Formula2 = "original spillover formula"
> End Sub
> '@
> 
> $reportFilePathWithMacros = $reportFilePath -replace '\.xlsx$', '.xlsm'
> Move-Item -Path $reportFilePath -Destination $reportFilePathWithMacros
> $xl = Open-ExcelPackage -Path $reportFilePathWithMacros
> $wb = $xl.Workbook
> $wb.CreateVBAProject()
> ($wb.VbaProject.Modules | Where-Object Name -EQ 'ThisWorkbook').Code = $thisWorkbookMacro
> Close-ExcelPackage -ExcelPackage $xl
> ```

Great, thank you so much for your help, i'm gon a try it.

**Comment by Emilius256** [comment]
Thanks, it works perfectly.
Thank you for your help.

**Comment by geoced** [comment]
Glad to be of help!

**Comment by dfinke** [comment]
Cool, gread to see `$wb.CreateVBAProject()` used. Very rare to see it in the wild :-)
