### ISSUE TITLE
Need Help: Conditional Formatting --> Wildcard/RegEx

### ISSUE THREAD

**Issue by evild3ad** [dfinke/ImportExcel#1336]
Hi,  

I would like to do some conditional formatting of specific file paths/device paths:  

Device Path 1: \Device\HarddiskVolume1\Users\\*\Downloads\
PowerShell: `$Import | Where-Object { $_."Device Path" -match "\\Users\\.*\\Downloads\\" }`
Note: Sub-directories of the Downloads folder are included.

`Add-ConditionalFormatting -Address $WorkSheet.Dimension.Address -WorkSheet $WorkSheet -RuleType 'Expression' -ConditionValue '=AND($F1="\Users\",$F1="\Desktop\")' -BackGroundColor "Red"`

Works, but it's quite dirty...do you know a better way to do it via Conditional Formatting?

Device Path 2: \Device\HarddiskVolume1\\
PowerShell: `$Import | Where-Object { $_."Device Path" -match "\\Device\\HarddiskVolume[0-9]\\[A-Za-z0-9_]*$" }`
Note: Sub-directories are not included. Root only.

Is it possible to use wildcards and/or RegEx to handle these device paths?

Thanks in advance!

**Comment by dfinke** [comment]
The conditional formatting is totally dependent on what Excel implements. I don't believe Excel supports regex. Quick google, nothing. You can set a simple conditional format, open Excel and look around the UI, maybe there is regex support.

**Comment by jhoneill** [comment]
Sorry I've looked at this a couple of times, and meant to post something. 

When I've hit this kind of thing - I use a hidden column. So my PowerShell outputs 11 columns where I want the first 10, and after sending it to excel I hide column K . Then my conditional formatting for A2...A99  might say if K2 = true, and this will apply K2 to A2, K3 to A3 etc. (Skip the title row, and ensure the rows line up). 
It's not perfect because if someone changes the value whatever drives the conditional formatting doesn't update, but for most things where the data is fetched by PowerShell and excel is presenting it, that's good enough
