### ISSUE TITLE
Convert XLS to XLSX

### ISSUE THREAD

**Issue by username-is-already-taken2** [dfinke/ImportExcel#143]
Hi there

I've used your module loads, thanks for writting it.  I've noticed that I get an exception if I use the import-excel function with .xls file.  This may be by design if not I can provide the exception details.

I wondered if there was a potentional feature request in being able to convert xls to xlsx files?

Saving my xls to an xlsx meant that I could carry on with using the import-excel function.

Best Regards

Gary

**Comment by dfinke** [comment]
Thank you.

The underlying libraries are EPPlus that use .NET to work with the Excel files. They do not support the `.xls` format. 

So, yes, you need to save the `xls` as an `xlsx` in order to work.

That too can be automated with PowerShell

Here it is done in C#  and could be ported to PowerShell.

http://stackoverflow.com/questions/18904561/programmatically-convert-excel-2003-files-to-2007/18904633#18904633

**Comment by jakedenyer** [comment]
Haven't tried this method but I too was having this issue with EPPlus. My solution for this was a bit different because my end goal was to use the XLS file with SSIS. 

I had another solution that would require Excel to be installed but who wants that dependency for their scripts? 

so my question is - does ClosedXML (the library in your solution above) require Excel to be installed?

**Comment by dfinke** [comment]
The PowerShell Excel module does require Excel to be installed. That link to StackOverflow using the interop libraries does require Excel. I believe (and have not confirmed) the `xls` files is the proprietary Microsoft format and can only be modified with Excel.

**Comment by NordbergKMD** [comment]
I have "ported" the stack overflow example to powershell:

> 
>     $File = "test.xls"
>     $xlWorkbookDefault = 51
>     $xlFixedFormat = $xlWorkbookDefault
>     $Excel = New-Object -ComObject "Excel.Application"
>     $Excel.Visible = $false
>     $Excel.Workbooks.Open($File) | Out-Null
>     $Excel.ActiveWorkbook.SaveAs($File + "x", $xlFixedFormat)
>     $Excel.ActiveWorkbook.Close()
>     $Excel.Quit()
> 

It requires Excel installed.
Opens $File and saves it as .xlsx, which can then be used with ImportExcel.

Hope it helps someone :)

**Comment by dfinke** [comment]
@NordbergKMD would you be up for forking the repo and adding this as a script in the module?

**Comment by dfinke** [comment]
Great!  If you could add this as a separate .ps1 file and a function inside, then it can be dot sourced from the .psm1

**Comment by NordbergKMD** [comment]
@dfinke I gave it an initial go: PR https://github.com/dfinke/ImportExcel/pull/192

Feel free to comment.
