### ISSUE TITLE
[Bug] Export-Excel with Append and StartRow offsets appended content

### ISSUE THREAD

**Issue by Eddga** [dfinke/ImportExcel#1444]
First a huge thank you to dfinke and all the contributors to this project.
I'm an IT administrator and use your PowerShell module in almost all my scripts to visualize and report data and am so grateful for this! 🫡
This issue is already (partly?) described in #1138 or #1167. But one didn't receive any answer and the other one couldn't be reproduced? I'm not quite sure what happened there.
But I'm currently running into the exact same issue running version 7.8.4 of the ImportExcel module.
I have an Excel table with content that looks similar to something like I've built in the attached Excel table and shown in the picture at the end of the post.
[Sample Excel File: BLA.xlsx](https://github.com/dfinke/ImportExcel/files/11301606/BLA.xlsx)
The table has a (multi-row) header above the actual content. And therefore I have to use the StartRow parameter.
Now I want to append some (new) content to this table and can't just import, add and export it because the table is heavily formatted and therefore have to use the Append switch.
You can use this code to reproduce the issue:
```
$path = Join-Path (New-Object -ComObject Shell.Application).NameSpace('shell:Downloads').Self.Path 'BLA.xlsx'
$content = Import-Excel -Path $path -StartRow 6
Export-Excel -InputObject $content -Path $path -StartRow 6 -Append -Show
```

Now the issue is that when using Export-Excel with the StartRow and Append parameters combined, the content will be sucessfully written and saved to the table but offset by a large amount of columns as shown in the second attached picture.
The offset doesn't seem to be something fixed. In my sample table it was set off by 57 columns, in the actual table it was 82 columns (counted from the last column containing original content).
If you run the code multiple times it will even add the content again with additional column-offset instead of appending it to the present offset content.

Thanks in advance for any help!
And please just tell me or ask if I'm missing any crucial information for proper issue reporting.
Best,
Eddga

<img src="https://user-images.githubusercontent.com/18622817/233790524-21e42895-bdf0-4a1b-a1c2-24a39bb68aeb.jpg" width="300">

![ExportExcelAppendOffset](https://user-images.githubusercontent.com/18622817/233790898-66316ba8-52d3-4194-97de-1de028bc9474.jpg)

**Comment by dfinke** [comment]
That's a feature! It backs up your data in the table 🙂

Joking. I will look into that.

**Comment by Eddga** [comment]
Ohhh! Now that makes sense. In that case I'd like to suggest to add a parameter "-backup" that will combine -append and -startrow automatically. 😅

You legend! Thanks a lot. 👍

**Comment by TinyMysticMind** [comment]
Hello Doug,
first of all big thanks to your very nice work for the great module.

I ran into the same issue and my analysis showed that replacing the cell line number does not work as expected.
The code location is in the file https://www.powershellgallery.com/packages/ImportExcel/7.8.4/Content/Public%5CExport-Excel.ps1
in line 140
`$headerRange = $ws.Dimension.Address -replace "\d+$", $StartRow`

If the RegEx expression is changed from "`\d+$`" to "`\d+([:]|$)`", it works as expected.

Here is the link for the regex test
https://regex101.com/r/GBAsgh/1

I wish you a lot of fun in further development.

**Comment by dfinke** [comment]
Thanks @TinyMysticMind for the detailed info and fix. 

I used my PowerShellAI module to explain both of the Regex. If you want to try the ChatGPT in the console: `Install-Module PowerShellAI`

![image](https://github.com/dfinke/ImportExcel/assets/67258/d5fa90d0-9df3-460a-aae8-808743cd3139)

**Comment by TinyMysticMind** [comment]
Hi Doug thanks for your reply.
That showed me that my suggestion is too complex chosen.

Explanation of "`\d+$`"
"`\d+$`"
Finds only characters with digits that are at the end of a string due to the anchor '`$`'.

Explanation of my proposed solution based on the exemplary cell range specification 
"D:\Reports1\_1\[ExcelFile1.xlsx]!Sheet_name!$A1:$FZ2"
In this cell range, the row number "1" of the start cell address "A1" is not at the end of a string. 
However, this must be adjusted so that the cell range at the start can be adjusted to the line of the end cell address "FZ2".

The regular expression "`\d+([:]|$)`" I originally proposed should be changed to "`\d+:`".

Explanation of "`\d+:`"
Expression:	`\d+` 
Explanation: Finds every character for a digit from 0-9
Expression: `:`
Explanation: Character ":" must follow a digit character.

The chosen restriction to the character "`:` "prevents the modification of characters with digits that do not belong to the line number of a start cell address.

Here is the URL for the RegEx test.
https://regex101.com/r/ttnB28/1

After further testing and analysis, I have updated my changes as follows.
The code location in the file 
https://www.powershellgallery.com/packages/ImportExcel/7.8.4/Content/Public%5CExport-Excel.ps1
in line 140
`$headerRange = $ws.Dimension.Address -replace "\d+$", $StartRow`

to
`$headerRange = $ws.Dimension.Address -replace "\d+:", $StartRow`


In this context, I had to make another change so that the output is in the correct row when there are no data rows after the header row.
To do this, I chose the following solution without exactly figuring out if it was the right place to make the adjustment.
Basis is the code of the file "https://www.powershellgallery.com/packages/ImportExcel/7.8.4/Content/Public%5CExport-Excel.ps1".
After adding between code lines 292 and 293 from the following code lines, the case also worked as expected.

`# Adjust the line counter if lines are to be appended, there is a header line, and there are no lines with data.`
`if($Append -and $script:Header -and ($ws.Dimension.End.Row -gt $row) ) { $row += 1 }`

**Comment by dfinke** [comment]
Cool, thanks for the follow up. I did not dig deeper. I thought the `$ws.Dimension.Address` returned `A1:A2`.

Tests need to be written to test the failure and then the solution.

**Comment by TinyMysticMind** [comment]
Hi Doug,

You're very welcome, thank you for your quick and open response.

You are right 
`$ws.Dimension.Address` returns "A1:A2"

My example was meant to represent the complete form of a cell reference to illustrate that the regular expression also works for the complete cell reference with a reference to an external file.
Changing "A1:A2" to "A2:A2" is the goal in all cases.

Have fun writing the tests and implementation.
I look forward to the version with the modification.

Best regards and keep up the good work. :)

**Comment by Eddga** [comment]
Hey @dfinke,
Primarily commenting to prevent the issue from being auto closed.
Is there anything I could do to support you here?
Best,
Eddga

**Comment by dfinke** [comment]
Time has become more limited to be able to resolve these

**Comment by scriptingstudio** [comment]
Can confirm. The same here. Got stuck with it.

**Comment by scriptingstudio** [comment]
**My case looks as following:**

![image](https://github.com/dfinke/ImportExcel/assets/17237559/4179e6a4-828e-46a1-88f7-193591b49afc)

**Code:**
```powershell
$table1 = ConvertFrom-Csv @"
Region,State,Units,Price
West,Texas,927,923.71
North,Tennessee,466,770.67
East,Florida,520,458.68
East,Maine,828,661.24
West,Virginia,465,053.58
North,Missouri,436,235.67
South,Kansas,214,992.47
North,North Dakota,789,640.72
South,Delaware,712,508.55
"@
$table2 = ConvertFrom-Csv @"
Region,State,Units,Price,Index
West,Texas,927,923.71,1
North,Tennessee,466,770.67,1
East,Florida,520,458.68,1
East,Maine,828,661.24,1
West,Virginia,465,053.58,1
North,Missouri,436,235.67,1
South,Kansas,214,992.47,1
North,North Dakota,789,640.72,1
South,Delaware,712,508.55,1
"@

$xlsx = "exceltables.xlsx"
if (test-path $xlsx) {remove-item $xlsx}
$excel = $table1 | Export-Excel -path $xlsx -WorksheetName tab1 -tablename table1
$excel = $table2 | Export-Excel -ExcelPackage $excel -WorksheetName tab1 -tablename table2 -Append -StartRow ($table1.count+5)
Close-ExcelPackage $excel -Show
```

`-StartRow` parameter does not work too.
**Workaround** is to omit `-Append` parameter.

**Comment by scriptingstudio** [comment]
I think the right expression for header would be:
```powershell
$headerRange = $ws.Dimension.Address -replace '\d' -replace ":|$","${StartRow}:" -replace ':$'
```

Then expression `$ws.Cells[$headerRange].Value | ForEach-Object -Begin { $Script:header = @() } -Process { $Script:header += $_ }` creates empty header because the range `$ws.Cells[$headerRange]` is empty. This expression does not work with `-Append` parameter.

Correct me where I am wrong.

**Comment by Eddga** [comment]
Hey @scriptingstudio,
I'm not really sure what your desired resulting table would look like.
But it doesn't look like your example is related to my described issue. My example is about a worksheet where the table header isn't located in the first row and you want to append content to this table. In your example your header indeed is in the first row.
If you want a combined table (which is what -append is for) just drop the -StartRow and -TableName parameters. If you're just using TableName for the formatting/design you could rather use -TableStyle Medium6 which is the default theme that is also used with TableName if no other style is set to be used. Or set TableName to the same for both exports. Given you dropped StartRow you will otherwise also receive a warning with different TableNames "Table range collides with table table1" which only makes sense as you're appending the content and the header of table2 would therefore collide with the last row of table1. So in this case it should either be
`$excel = $table1 | Export-Excel -Path $xlsx -WorksheetName tab1 -TableName table1 -PassThru
$excel = $table2 | Export-Excel -ExcelPackage $excel -WorksheetName tab1 -TableName table1 -Append -PassThru`
or
`$excel = $table1 | Export-Excel -Path $xlsx -WorksheetName tab1 -PassThru -TableStyle Medium6
$excel = $table2 | Export-Excel -ExcelPackage $excel -WorksheetName tab1 -Append -PassThru`
But be aware that your Index column will not appear in this case as it is only part of table2.

If you want two separate tables in the same sheet drop the Append parameter. Because in that case you're not appending content to an existing table but rather adding a second table.
`$excel = $table1 | Export-Excel -Path $xlsx -WorksheetName tab1 -TableName table1 -PassThru
$excel = $table2 | Export-Excel -ExcelPackage $excel -WorksheetName tab1 -TableName table2 -PassThru -StartRow ($table1.count+5)`

Other than that I think that you're correct:
`$headerRange = $ws.Dimension.Address -replace '\d+', $StartRow`
should be the solution. At least the variable name headerRange suggests that it should contain the range of the header only and therefore both numbers of the dimension.address range should be replaced with $StartRow

**Comment by Eddga** [comment]
Should I keep commenting to keep the issue alive? I feel like that's not how it's meant to be and I don't want to annoy anybody.. 😅

**Comment by dfinke** [comment]
No worries. I don't have an answer and need to look at this down the road. - Thanks
