### ISSUE TITLE
Feature Request: Apply Sensitivity Label

### ISSUE THREAD

**Issue by StevenDTX** [dfinke/ImportExcel#1600]
https://support.microsoft.com/en-us/office/apply-sensitivity-labels-to-your-files-and-email-2f96e7cd-d5a4-403b-8bd7-4cc636bae0f9

Thanks!

**Comment by dfinke** [comment]
There is not a way to do that with the file structure supported by the module.

**Comment by Viajaz** [comment]
I was considering adding the this functionality myself but I quickly discovered the blockers. I'm documenting them here for others that were considering doing the same thing, even if it may seem self-evident to some people.

[EPPlus 8 supports Sensitivity Labels](https://github.com/EPPlusSoftware/EPPlus/wiki/Working-with-Sensibility-Labels) but ImportExcel uses EPPlus 4 due to the licensing changes on newer versions (#979) so that path is a no-go.

It should be possible with [Microsoft Information Protection SDK](https://learn.microsoft.com/en-us/information-protection/develop/concept-apis-use-cases) but that means big binary libs and all the awful PowerShell wrapper code to go with it as well as the async issues, at that point, it might be cleaner to just port/rewrite the whole ImportExcel module as a PowerShell Binary Module in C#.

I also think a MIP SDK implementation would have to stick with temporary decrypted files instead of streams which wouldn't be compliant with a number of compliance environments that utilise Sensitivity Labels to begin with.
