### ISSUE TITLE
Create an index page of sheets

### ISSUE THREAD

**Issue by jameseholt** [dfinke/ImportExcel#245]
Hi I'm loving this module still learning so much about what I can do with it!

One thing that would be a really great enhancement would be if it could create an index page with hyperlinks to each sheet.  This is really useful when you have (1) a lot of sheets and (2) nice long descriptive sheet names isn't feasible.  Hope this is something you could consider.

**Comment by DarkLite1** [comment]
I'm not an Excel expert, but a `hyperlink` in Excel is actually just a regular formula I believe.  An example can be found (here)[https://www.ablebits.com/office-addins-blog/2014/05/15/excel-insert-hyperlink/#hyperlink-function].

**Comment by dfinke** [comment]
@DarkLite1 Does that work when using `Export-Excel`. Early on I tried it using the EPPlus API and had no luck. I Don't remember if I tried it with a formula.

**Comment by DarkLite1** [comment]
Very strange... When I try the following with a formula in it, there is no problem:

```
$Params = @{
    Path = '.\test.xlsx'
    AutoSize = $true
}
Remove-Item  $Params.Path -EA Ignore
 [PSCustOmobject]@{
        Formula1  = '=SUM(B2:C2)'
        Number1   = '15'
        Number2   = '85'
    } | Export-Excel @Params 
```

But when I try this, it's just throwing out a corrupt Excel file because of the formulas. And I'm confident the formulas are correct because I tested them in Excel manually.

```
Get-Service | Select-Object -Property Status, Name, DisplayName, StartType | Export-Excel @Params -WorkSheetname Sheet2
Get-Process | Select-Object -Property Name, Company, Handles, CPU, VM | Export-Excel @Params -WorkSheetname Sheet3

'Navigation', '=HYPERLINK("#Sheet2!A1";"Go to second sheet cell A1")', '=HYPERLINK("#Sheet3!B7";"Go to third sheet cell B7")' | Export-Excel @Params -WorkSheetname Sheet1 -Verbose
```

The verbose messages show me that the formulas are correctly added as formulas. However, they seem not be accepted by Excel. Am I missing something obvious here?
