### ISSUE TITLE
Exchange Online removes the attachment

### ISSUE THREAD

**Issue by Clawz2k** [dfinke/ImportExcel#254]
Attachment gets removed and a blank txt file gets added. Content of the file is "This attachment was removed."

If I open the excel file that was generated, save it, then email it again, that works fine.

`Install-Module ImportExcel -scope CurrentUser
$file = "C:\temp\Book1.xlsx"
echo a b c 1 $true 2.1 1/1/2015 | Export-Excel $file
$smtpServer = "some mailhost"
$att = new-object Net.Mail.Attachment($file)
$msg = new-object Net.Mail.MailMessage
$smtp = new-object Net.Mail.SmtpClient($smtpServer)
$msg.From = "some email"
$msg.To.Add("some email hosted on exchange online")
$msg.Subject = "Notification from email server"
$msg.Body = "Attached is the email server mailbox report"
$msg.Attachments.Add($att)
$smtp.Send($msg)
$att.Dispose()`

**Comment by dfinke** [comment]
Hmm. Sorry I don't have experience with Exchange online.

**Comment by CrashM** [comment]
I have the same issue.  Was going to raise it separately, but saw that the issue is already posted.

When a file created by Export-excel is subsequently emailed via Send-MailMessage to Office365 (Exchange Online), Microsoft email scanner is striping the attachment.  I cannot via programming open and re-save the output since the whole idea of Export-Excel was to be able to do this on a server without Office installed.

Can we determine why Microsoft doesn't recognize the xlsx file as a valid Excel file?

Would it be helpful for you to be able to compare binary copies of the two states of the file? Or is this something for EPPlus to look at?

P.S.  There appears to be an issue logged with EPPlus [https://github.com/JanKallman/EPPlus/issues/168](https://github.com/JanKallman/EPPlus/issues/168) where they even propose a fix.
