### ISSUE TITLE
Import-excel as strings

### ISSUE THREAD

**Issue by freke70** [dfinke/ImportExcel#289]
I'm trying to import an excel file.
Some of the cells have dates, but when they are imported with "Import-excel" they come out in the wrong format.

For example:
14-May-18 becomes: 43234

The type when I check it's variable is:
```
IsPublic IsSerial Name                                     BaseType                                                                                   
-------- -------- ----                                     --------                                                                                   
True     True     Double                                   System.ValueType       
                                                                    
```

Is there a way to import all the data from the excel sheet as strings?
No need for numerical value's.

Thanks for helping me!

**Comment by dfinke** [comment]
Could to post an Excel file with the problem?

**Comment by supersjimmie** [comment]
I guess the point here is that a date is actually just a number, with the cell setup to display it as a date.
That number represents the number of days since 1/1/1900.

So a date in a cell is not stored as a date, it is stored as a number. Therefor you can only retrieve that number. The only way to get it as a string is to write your own function that converts a number to a string in the date format.

To clarify, dates are stored as this kind of numbers:
https://support.office.com/en-us/article/datevalue-function-df8b07d4-7761-4a93-bc33-b7471bbff252
and
https://community.alteryx.com/t5/Data-Sources/How-to-convert-the-Excel-numerical-date-to-date-in-Alteryx/td-p/11184

**Comment by dfinke** [comment]
Yes, `[datetime]::FromOADate((get-date).ToOADate())`

> Returns a DateTime equivalent to the specified OLE Automation Date
