### ISSUE TITLE
Export-Charts keeps excel open in background

### ISSUE THREAD

**Issue by supersjimmie** [dfinke/ImportExcel#327]
I am using the following:
https://github.com/dfinke/ImportExcel/blob/master/Export-charts.ps1
For exporting the graphs to jpg files.

After calling this, I notice that Excel keeps running in the background, and very annoying is that I get a "save yes/no/cancel" when I manually want to open the excel file afterwards.

It seems that the Quit() part keeps waiting for that y/n/c question in the background?

I tried to close everything with:
```
    $excelApp.Workbooks.Close()
    $excelApp.Quit()
    [System.GC]::Collect()
    [System.GC]::WaitForPendingFinalizers()
    [System.Runtime.Interopservices.Marshal]::ReleaseComObject($ExcelWorkbook)
    [System.Runtime.Interopservices.Marshal]::ReleaseComObject($ExcelApp)
    Remove-Variable -Name ExcelApp
```
But that does not solve it.

**Comment by jhoneill** [comment]
Adding 
`Remove-Item -Path Variable:\excelApp` 
after the  quit()  Excel closes the way we'd expect. 
I'm not sure if this has changed with different releases of Excel or if the old code I raided to create this had the same bug. This will be in the next pull request I submit but for now you can just add that line.  

I can't repro the "Save ... yes/no/cancel" but the because of the way the library creates graphs, pivots and so on (the specification is there, but calculations haven't been done nothing is drawn) it is quite possible that opening XLSx file will automatically make the Excel think there have been changes.

**Comment by jhoneill** [comment]
I can't repro the "Save ... yes/no/cancel" but the because of the way the library creates graphs, pivots and so on (the specification is there, but calculations haven't been done nothing is drawn) it is quite possible that opening XLSx file will automatically make the Excel think there have been changes. 

Excel will close when the variable goes away ; normally $excelApp only exists in the scope of the PS1 file, and when the script exits, so does Excel.exe. but I have seen this take 10-15 seconds.   Various debugging activities seem to cause the variable to persist , running 
`Remove-Item -Path Variable:\excelApp`  
should force Excel to close when this happens. 

If Excel is stopping because there it thinks there are unsaved changes , then inserting 
`$Excelworkbook.close($false,$null,$null)` 
before the quit line should close the work book _without saving changes._  As it appears in the post above I think it will ask if you want to save changes. 

Could you let me know if that fixes it for you? If it helps for some files (my test ones work without it) then I'll add it to the next pull request I submit.
Thanks

J

**Comment by supersjimmie** [comment]
I think adding 
```$excelApp.DisplayAlerts = $false```
has solved it for me.
