### ISSUE TITLE
Make cell data an HTML link

### ISSUE THREAD

**Issue by lastusrnameon3** [dfinke/ImportExcel#348]
Would like to be able to export some data from our ticketing system. 
I would then like to be able to make one of our cells "Ticket number" an HTML link that leads to the ticket number

**Comment by dfinke** [comment]
Yeah, I looked into that a while ago. Might be more easily doable now with Open/Close package and Set-Format type approach.

**Comment by jhoneill** [comment]
Cell objects do have a hyperlink property. One way to do this would be for Add-CellValue to trap something of type system.uri and set the hyperlink property  ... this would work for piping in an object where one property (or more than one) is a URI. 

Someone can also write their own code which goes down a column setting a custom Hyperlink, but this going to be specific to each scenario - the generic way would be to handle URI properties.

**Comment by dfinke** [comment]
Played with it last night. I have an example in the examples folder.  It has issues and is worth revisiting.

**Comment by jhoneill** [comment]
Yeah, if I import something with hyperlinks the style ID on those cells is 107 and the style name is hyperlink, but if I set the ID it deletes the style and sets the name to null. If I set the name to hyperlink the Style comes back, but the name is set to "Normal"

But I inserted this in the switch part of Add-CellValue 
```
{$_ -is [URI] } {
                    #region Save a hyperlink
                    $TargetCell.Value      = $_.AbsoluteUri
                    $TargetCell.HyperLink  = $_ 
                    $TargetCell.Style.Font.Color.SetColor([System.Drawing.Color]::Blue)
                    $TargetCell.Style.Font.UnderLine = $true
                    Write-Verbose "Cell '$Row`:$ColumnIndex' header '$Name' add value '$($_.AbsoluteUri)' as Hyperlink"
                    break
                    #endregion
                }
```

**Comment by jhoneill** [comment]
I have added the code above to my latest check in - which needs more testing before being pulled into the main branch: if anyone wants to test it, it is at https://github.com/jhoneill/ImportExcel/blob/master/Export-Excel.ps1

The full list of things changed is
•Added MoveToStart, MoveBefore and MoveAfter Parameters
•Added support for URI item properties. If a property is of type URI it is created as a hyperlink
•Fixed issue where AutoNamedRange, NamedRange, and TableName do not work when appending to a sheet which already contains the range(s) / table
•Fixed issues when pivottables / charts already exist and an export tries to create them again.
•Allowed PivotFilter and PivotDataToColumn, ChartHeight/width ChartRow/Column, ChartRow/ColumnPixelOffsets, to be passed in -PivotTableDefinition and specified when running New-PivotDefinition.
•Bad column-names specified for Pivots now generate warnings instead of throwing.
•Removed the need to specify a fill type when specifying a title background color
•"flattened out" small "called-once" function , add-title, convert-toNumber and Stop-ExcelProcess.

**Comment by jhoneill** [comment]
Please note if testing the my unmerged export excel, please use this link https://github.com/jhoneill/ImportExcel/commit/520bb079e5d863931d650e369e7faa9ab7d973d1#diff-2312e8cdbe09401310dc615fad4e8d83  the commit I did this evening needs more changed files.
