### ISSUE TITLE
PivotFilter

### ISSUE THREAD

**Issue by FetFlex** [dfinke/ImportExcel#349]
Hi All,

I'm trying to create a filter on a PivotTable. I got it working with the -PivotFilter 'Status'.

Then i was wondering, is it possible to set the filter from the Import-Excel? So it starts filtered like "status -eq 'Active'" ?

**Comment by jhoneill** [comment]
Had a  look, 
1. -PivotFilter and -PivotDataToColumn aren't supported in  -PivotTableDefinition ; shouldn't be too complicated to add them 
2.  Internally the PivotTable object uses the name "Pagefield" for what the excel UI calls a "filter". If you open a workbook with a filter applied, select some items and save them, the "items" property contains one item per selectable item on the list but this just has a zero length text field, so I can't way to find what is set in Excel, so it doesn't look like there is a way to add them through the library.

**Comment by FetFlex** [comment]
@jhoneill  Thanks for the response. Maybe it will be implemented one day. But thanks for the looking in to it.

**Comment by jhoneill** [comment]
I've put Move* parameters and added extra parameter support to PivotTable Definitions  in my latest check in - which needs more testing before being pulled into the main branch:  if anyone wants to test it, it is at   https://github.com/jhoneill/ImportExcel/blob/master/Export-Excel.ps1 

The full list of things changed is 
- Added MoveToStart, MoveBefore and MoveAfter Parameters 
- Added support for URI item properties. If a property is of type URI it is created as a hyperlink
- Fixed issue where AutoNamedRange, NamedRange, and TableName do not work when appending to a sheet which already contains the range(s) / table  
- Fixed issues when pivottables / charts already exist and an export tries to create them again.   
- Allowed PivotFilter and PivotDataToColumn, ChartHeight/width ChartRow/Column, ChartRow/ColumnPixelOffsets,  to be passed in -PivotTableDefinition and specified when running New-PivotDefinition. 
- Bad column-names specified for Pivots now generate warnings instead of throwing.
- Removed the need to specify a fill type when specifying a title background color
- "flattened out" small "called-once" function , add-title, convert-toNumber and Stop-ExcelProcess.

**Comment by jhoneill** [comment]
Please note if testing the my unmerged export excel, please use this link https://github.com/jhoneill/ImportExcel/commit/520bb079e5d863931d650e369e7faa9ab7d973d1#diff-2312e8cdbe09401310dc615fad4e8d83  the commit I did this evening needs more changed files.
