### ISSUE TITLE
PivotChart Manipulation

### ISSUE THREAD

**Issue by tbrock47** [dfinke/ImportExcel#350]
I investigated this for awhile today, but I don't see options to manipulate a chart created from a pivot table (-IncludePivotChart) similar to the parameters in New-ExcelChart like "-Width" and "-Height".

I may be going about this all wrong, but I can get a pivot chart to generate easily and include a chart with my desired chart type all the same worksheet, but that is it. I don't see a way to dictate chart size, placement and such.

Ideally, my goal is to generate a single pivot table from the source data, and then include a chart for that pivot table on its own worksheet. I can do all of that except placing the chart in its own dedicated worksheet. I can move the chart using the GUI to its own worksheet after the fact, but I want to eliminate that manual step.

**Comment by jhoneill** [comment]
Good time to ask this question ... #345 & #349 refer to wanting to add more properties to the Pivot table definition (I've linked to these on #342 where I've listed multiple things I'm doing). 

What I have just done is to add  ChartHeight , ChartWidth, ChartRow, ChartColumn, ChartRowOffSetPixels  and ChartColumnOffSetPixels to New-PivotTableDefinition and support for it in Export-Excel if passing PivotTable Definitions.  
(because command line specified PivotTables and Definition specified ones are processed separately this I'd prefer to avoid adding these as command line options) 

I have just committed these changes to my branch - the new version is here 
https://github.com/jhoneill/ImportExcel/blob/master/Export-Excel.ps1 

It has had **minimal testing** - I have literally just run example 11 from the Export-Excel help with extra parameters. I have more testing to do and a couple of other files to check in before I send a pull request to @dfinke  to bring it into the main branch, if you would like to download the this one file and provide any feedback in the meantime, that would be very welcome.

**Comment by jhoneill** [comment]
Please note if testing the my unmerged export excel, please use this link https://github.com/jhoneill/ImportExcel/commit/520bb079e5d863931d650e369e7faa9ab7d973d1#diff-2312e8cdbe09401310dc615fad4e8d83  the commit I did this evening needs more changed files.
