### ISSUE TITLE
Fill in Excel - Select Radio Button, Pick a value from an existing drop-down

### ISSUE THREAD

**Issue by archanashridhar** [dfinke/ImportExcel#390]
I am trying to fill in an existing .XLSM file using this powershell excel module. It works well for most of my requirements. I am able to fill in values for cells and format. However, the excel file has form controls like radio buttons and drop-down lists. Is it possible to use this module to have a radio-button checked or unchecked and also select value from the drop-down ?

**Comment by jubejube56** [comment]
Yes it is though technically I think it is done through a VBA module.

`$excel.Workbook.CreateVBAProject()
$excel.Workbook.CodeModule.Name = "Module1"
$excel.Workbook.CodeModule.Code = "Private Sub Workbook_Open ()`r`n" + `
"With ActiveSheet.OLEObjects.Add(ClassType:=""Forms.OptionButton.1"", Link:=False, DisplayAsIcon:=False, Left:=50, Top:=80, Width:=100, Height:=15)`r`n" + `
"End With `r`n" +`
"With ActiveSheet.OLEObjects.Add(ClassType:=""Forms.OptionButton.1"", Link:=False, DisplayAsIcon:=False, Left:=50, Top:=100, Width:=100, Height:=15)`r`n" +`
"End With `r`n" +`
"ActiveSheet.OLEObjects(""OptionButton2"").Object.Value = True `r`n" +`
"End Sub"`

Something like this will create 2 radio/Option Buttons and selects the second one when you open the workbook. $excel is an ExcelPackage you can PassThru from an ExportExcel call or otherwise.

**Comment by Mike-Crowley** [comment]
Add-ExcelDataValidationRule 
https://github.com/dfinke/ImportExcel/blob/master/mdHelp/en/Add-ExcelDataValidationRule.md
