### ISSUE TITLE
Some formatting or unhideing is impossible

### ISSUE THREAD

**Issue by CamFlyerCH** [dfinke/ImportExcel#400]
While testing the fix for Issue #397 I found that some of the parameter presence testing is bad or some function are impossible to reverse. This affects the following functions:

Set-Format: (and some parameters in Set-Row, Set-Column and Add-ConditionalFormatting too)
- -Hidden, is a switch parameter, but there is no unhide
- -WrapText, can only be enabled, but there is no disable
- -Bold, Italic, StrikeThrough and Underline, can only be undone all together with ResetFont, not seperatly
- -Width and -Height can't be set to 0
- -Value, can not be cleared

Export-Excel
-HideSheet , but no unhide

(This list is incomplete, but you get the point)

Converting switches to Boolean parameters would help, but this would be a breaking change.
Testing for used parameters would help to set 0 oder nothing. Example: 
`$PSBoundParameters.ContainsKey('MyParameter')`

**Comment by jhoneill** [comment]
So a quick explanation of how we got to where we are : it was expected Export-Excel and set-format, set-column and Set-Row will be working on newly created worksheets, by default things will only be hidden, wrapped, bolded etc by one of these commands. So the slightly glib advice was (e.g.) if you don't want something hidden, don't hide it; don't set values you want cleared and so on.  I didn't foresee a need to turn wrapping off, clear values etc, and I don't think @dfinke  did either.  
I added Reset font for the case where I set two overlapping ranges and if one set bold and one set italic I wanted the second to be able to say "Italic and nothing else"   

Booleans and psBoundParameters are both problematic : consider 
```
function test {
param ([boolean]$b,
       [int]$i ,
       $j = 10 
       )
if ($b -eq $null)  {Write-Host 'b is null' } 
if ($b -eq $false) {Write-Host 'b is false' } 
write-host "Bound paramter i = '$($PSBoundParameters['i'])'"
write-Host "Variable i = $i" 
write-host "Bound paramter j = '$($PSBoundParameters['j'])'"
write-host "Variable J = '$j'"
}

test 
```

Most people would not expect b to return false ;  but it does (Powershell converts the Null value of B to a Boolean, to get round this you have to use a [nullable[Boolean]]) . 
A standard Boolean means that 
 `set-format … -bold $true ; set-format … -italic $true ` 
leaves bold unset, because the second command implies `-bold $false -underline $false` etc.

The main reason for not using Booleans is requiring $true to be specified when $false is [almost] never expected is poor style; you can specify a switch with a value (e.g. when a function which a switch wants to pass it on to another function it call` f2 -switch:$mySwitchParam` or you can explicitly write` -bold:$false` ) 

PsboundParamters doesn't give you parameter _defaults_ it only tells you if the parameter was specified explicitly. (which is why it is named BOUNDParamters and not ParameterValues). But this makes `$PSBoundParameters.ContainsKey('MyParameter')` a more reliable test for "was specified" than "does the parameter convert to true" - doing some checks I found some enum values come back as false so won't work in set-format. 
 
So … I've made these changes,  

- set-format uses `$PSBoundParameters.ContainsKey('MyParameter') so that `-Switch:$False` and zero values or enums which translate to zero (and hence false) are all processed
- Set-format sets to the [Boolean]Switch   not true , so that `-switch:$false `can be used (e.g. -`Bold -italic:$false`) 
- Set-Row and Set-Column now call set-format rather than doing their own formatting. 

Eventually I'll support hide using wildcards and add a show which uses also wildcards in Export-Excel, so you can hide "all sheets except...", or unhide hidden sheets.

**Comment by jhoneill** [comment]
@CamFlyerCH  thanks for your input : the commits above implement the following: 

- -Empty and Zero values (including some Enums which used zero) will be set if passed 
- -Hidden -WrapText, -Bold, -Italic, -StrikeThrough and -Underline, all work with :$false; this syntax is not commonly used so I've added a note to the help to say "use -bold:$false to remove bold" etc
- Export-excel now supports -Hide *  (and other wildcards) and -Unhide ; because at least one sheet must be visible, if NOTHING is visible after hide and unhide are processed, the current sheet is revealed.

**Comment by CamFlyerCH** [comment]
@jhoneill  Wow, that's some great explanation and some serious work you managed to do to many of the functions.  Right now I can't invest time for testing all of this, but I sure it will be good !
