### ISSUE TITLE
Inserting Images - is this possible?

### ISSUE THREAD

**Issue by Penkethboy** [dfinke/ImportExcel#406]
Basically i'm creating a report and want to jazz it up a bit with a logo or two.

Cant see any methods to do this in examples or in past/current issues.

Is it possible and i just missed it?
Would want to control the size, position etc of the image Inserted

Thanks

**Comment by jubejube56** [comment]
Indeed it is.

First you'll need to PassThru an ExcelPackage, then get a worksheet from that package (I used $overviewSheet because that is what I am working on rn.

Then do these 2 lines.

`$imagePath = (get-item "C:\Users\tester\Documents\Excel\Desert.jpg")

$image = $overviewSheet.Drawings.AddPicture("testImage", $imagePath)

$image.SetSize(20)
$image.SetPosition(5,0,5,0)`

The first line gets a physical image (From what I read this particular method only works with JPEGs), second line adds it to the particular worksheet. SetSize() sets the image to a percentage of it's original size. SetPosition sets the position of the image, 1st parameter is the row, second is row offset in pixels, third is column, fourth is column offset in pixels.

**Comment by dfinke** [comment]
Great question @Penkethboy, thanks for the answer @jubejube56. Love the community.

This could be a nice feature to add to the overall library and make it easier to accomplish.

**Comment by jhoneill** [comment]
When I played with it earlier it seemed to have issues sizing the images I gave it. It doesn't size the image by the same ratio in X and Y dimensions. It's better at small sizes, 100% the image is scaled to 95% on Y and 62% on X …

**Comment by jhoneill** [comment]
Pretty sure it is:  from what I can see poking around in the file, it specifies cell and offset for opposite corners - these are the "from" and "to" properties of the image object , I'm guessing they're calculated with constants that don't work.

**Comment by Penkethboy** [comment]
Ok as i'm new to using passthru - i must be missing something as i cant get this to work

My code
"$file = "$PSScriptRoot\ImageTest.xlsx"

$xlPkg =  Export-Excel $file -PassThru

$ws = $xlPkg.Workbook.WorkBook[1]

$ImagePath =  (get-item  "$PSScriptRoot\test.jpg")
$Image = $ws.Drawings.AddPicture("testImage", $imagePath)

$image.SetSize(20)
$image.SetPosition(5,0,5,0)

$xlPkg.Save()
$xlPkg.Dispose()"

Fails on the $image line with
"You cannot call a method on a null-valued expression.
At S:\Coding\PowerShell\TestExcel\MultipleTables.ps1:59 char:1
+ $Image = $ws.Drawings.AddPicture("testImage", $imagePath)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull"

the image path is valid and get-item works fine

**Comment by Penkethboy** [comment]
arrrrrrrrrrrrrh
Workbooks not workbook
:)

**Comment by Penkethboy** [comment]
For reference png files work as well as jpg image files
