### ISSUE TITLE
Excel Date column processing

### ISSUE THREAD

**Issue by LouFarho** [dfinke/ImportExcel#429]
I have seen a couple closed issues regarding a column with a date. Yet, I am at a loss to understand how I am to retrieve the Formatted value of the column. The column Format was set to Short Format. Yet, when processing in my script I keep getting a double value. 

I am looping thru the rows of the spreadsheet accessing each column for processing into a SharePoint list. 
I tried various things to try and get a string formatted date but haven't gotten it . 
For eaxmple
$row.DueDate

Returns 43465 a double value type object. 
The formatted date is 12/31/2018 in the cell for example

**Comment by dfinke** [comment]
```powershell
[datetime]::FromOADate(43465)

Monday, December 31, 2018 12:00:00 AM
```

**Comment by jhoneill** [comment]
just to expand what @dfinke  said, I wrote somewhere else : 
Excel does not have dates as such. It uses numbers which count the number of days from January 1 1900 , with the fractional part representing the time of day.
When Importing data from an XLSx file, EPPlus - the library that the module uses - will recognize a date if it is formatted with one of built in date formats ,otherwise it will see a number. Custom date formats may result in importing as a number. If this happens You can convert the number in PowerShell with 
`if ($x -isnot [datetime]) {$x = [datetime]::FromOADate($x)}`

The built in formats are
```
14      mm-dd-yy but Localized on load 7/27/2018 (US)	27/07/2018 (most others)	
15	dd-mmm-yy     27-Jul-18 (English)  
16	dd-mmm        27-Jul	(English)	
17	mmm-yy        Jul-18	(English)	
18	h:mm AM/PM    2:41 PM	  
19	h:mm:ss AM/PM 2:41:27 PM
20      hh:mm         14:41
21	hh:mm:ss      14:41:27	
22	m/d/yyyy h:mm Localized 7/27/2018 14:41 (US) 27/07/2018 14:41 (Most others)
45	mm:ss	      41:27	
46	[h]:mm:ss     1039406:41:27
47	mm:ss.0	      41:27.2	

```
**Any other date format will come out of EPPlus, as a number.**

**Comment by LouFarho** [comment]
Thank you gentlemen! 
@dfinke I will update the script and give that a try today

@jhoneill I had seen this note of yours in one of the closed cases abut the format. I had set the format for the column from General to Short Date which I believe you said was format 14. Alas, it still was coming back as a double.
