### ISSUE TITLE
Need to select the cell, press F2, then enter for the formula to work

### ISSUE THREAD

**Issue by dfinke** [dfinke/ImportExcel#451]
Module version 5.3.3. I think there may be an issue for similar behavior.

You need to select B2, press F2, then enter for it to work.

```powershell
$xlfile = "$env:TEMP\vlookup.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$xlpkg = convertfrom-csv @"
Fruit,Amount
Apples,50
Oranges,20
Bananas,60
Lemons,40
"@ | Export-Excel $xlfile -PassThru -AutoSize -AutoNameRange -TableName FruitDataset

$ws = $xlpkg.Workbook.Worksheets["Sheet1"]

Set-Format -WorkSheet $ws -Range "A7" -Value "Apples"
Set-Format -WorkSheet $ws -Range "B7" -Formula "=vlookup(A7,FruitDataset,2,False)"

Close-ExcelPackage $xlpkg -Show
```

![image](https://user-images.githubusercontent.com/67258/46414354-edde0000-c6f0-11e8-9ca1-7daac2712ad8.png)

**Comment by jhoneill** [comment]
Formula needs to be `"=vlookup(A7,FruitDataset[],2,False)"`

Excel hides the [] from the user but uses that to designate a table rather than a named range. If you [F2] it changes that internally (load it back in PowerShell to see) but doesn't show the difference. 
Internally it doesn't store the "="  either, but beyond stripping the = sign parsing formulas to spot these kinds of syntax errors is way too difficult !

**Comment by ili101** [comment]
I'm not 4566t64556y66656656t5r
