### ISSUE TITLE
Set-ExcelRow sum on specified columns?

### ISSUE THREAD

**Issue by sturag** [dfinke/ImportExcel#476]
Im struggeling with Set-ExcelRow, i want to set a sum on specified columns, if i use -Value {"=sum($columnName`2:$columnName$endrow)" } then i get sum on all columns, but i only want to have it on columns D,G,J,I, is this possible? Thanks

**Comment by jhoneill** [comment]
Not directly  but you can do this 
`$r = set-row -Worksheet $WORKSHEET -Value  {"=sum($columnName`2:$columnName$endrow)" }  -PassThru
`

So now $r holds the row you just set and $r.row is the row number and
`
foreach ($col in "A","C","F") {$ref= $col + $r.row ; $WORKSHEET.Cells[$ref].value = $null}
`
Clears the cells where you don't want the totals.

**Comment by sturag** [comment]
OK, thanks, thats a start! Is it also possible to have sum on other columns (same row) with a different NumberFormat?

**Comment by jhoneill** [comment]
If you want all the totals to have the same format add` -Numberformat "0.00"`  or whatever format string

Or you can do something like that the example for values, but instead of setting the values, do this
`$WORKSHEET.Cells[$ref].Style.NumberFormat.Format = "0.00" `

If every one needs a different format you can get rid of the loop. and just have 
`$ref= "Z" + $r.row ; $WORKSHEET.Cells[$ref].Style.NumberFormat.Format`

**Comment by sturag** [comment]
Great! That will work! Thanks
