### ISSUE TITLE
Random Testing - Set-Format BorderAround - Doesnt seem to apply properly

### ISSUE THREAD

**Issue by pkarunkar** [dfinke/ImportExcel#524]
```
[pscustomobject]@{
    First = 'Boe'
    Last = 'Prox'
    ExtraInfo = 1
    State = 'NE'
} | Export-Excel C:\Users\PavithrasagarK\Desktop\Newfolder\test.xlsx

$excel = Open-ExcelPackage C:\Users\PavithrasagarK\Desktop\Newfolder\test.xlsx 
Set-Format -Address $excel.Workbook.Worksheets[1].Cells -BorderAround Thick
Close-ExcelPackage $excel 

Invoke-Item C:\Users\PavithrasagarK\Desktop\Newfolder\test.xlsx
```

BorderAround is applying to the left and right borders outside the filled data. 

![image](https://user-images.githubusercontent.com/44933985/51224879-fb24a080-1915-11e9-8606-7390b272bd0d.png)

Similar issues in other border styles. Am I doing something wrong?

**Comment by pkarunkar** [comment]
ok I guess it is since I havent specified Range and applying it to $excel.Workbook.Worksheets[1].Cells entire cells in sheet1. Is there a better way to wrap the broders around the usedRange. ?

**Comment by jaswicki** [comment]
I needed a Thick Border around some cells on my Summary sheet I created. Here is my code:

`$f = "c:\TEMP\JNJGPOReport.xlsx"
$pkg = Export-Excel -Path $f -AutoSize -PassThru
$ws = $pkg.Workbook.Worksheets["SUMMARY"]`
Set-Format -WorkSheet $ws -Range B2:G8 -BorderAround Thick

Since the number of rows of my summary data can vary but my columns are always B to G I put a counter into a foreach loop and then I can create my range as B2:G$i and it worked like a charm.

**Comment by dfinke** [comment]
You can also use `$workSheet.Dimension` to get the total number of rows and columns.
