### ISSUE TITLE
Export friendly name of hyperlinks

### ISSUE THREAD

**Issue by DarkLite1** [dfinke/ImportExcel#544]
Consider the following code:

```powershell
Remove-Item .\test_share.xlsx
$Test_data = @"
Link
=HYPERLINK("\\localhost\s$\Test\PC 1.xlsx"; "PC1")
"@ | ConvertFrom-Csv
$test_data | Export-Excel .\test_share.xlsx
```

The problem is that it doesn't seem possible to add a friendly name to a link. It appears that the following code in `Export-Excel` would fix this:

```powershell
$TargetCell.HyperLink = "\\localhost\s$\Test\PC 1.xlsx"
$TargetCell.Value = "PC 1"
```

But I don't really understand the decision process regarding `[System.Uri]`. @jhoneill , can you have a look how this would be best added? At the moment it just enters the clause for a regular formula `{($_ -is [String]) -and ($_[0] -eq '=')} {`.

When we try the following, we get  the error `Reference is not valid` in Excel:

```powershell
$Link = New-Object -TypeName OfficeOpenXml.ExcelHyperLink -ArgumentList  "\\localhost\s$\Test\PC 1.xlsx", "PC 1"
$Link | Export-Excel .\test_share.xlsx
```

**Comment by jhoneill** [comment]
Looks like the formula should have a comma, not a semi colon. 

There I've had a range of issues with UNC names - excel makes them into file URLs with an extra / in them so they become something like file:///\\server\share\path 
And EPPlus appears to corrupt some in that format.

**Comment by DarkLite1** [comment]
That was my first instinct too, that it should've been a comma instead of a semicolon. However, bot end up in a corrupt Excel file. So no luck there... 

The only solution that works is this one:
```powershell
$TargetCell.HyperLink = "\\localhost\s$\Test\PC 1.xlsx"
$TargetCell.Value = "PC 1"
```

But I don't know how to fit it in the module properly so other stuff doesn't get broken.

**Comment by jhoneill** [comment]
Usually the corrupt file message is because what has been written as the content of a cell is something the Excel UI would not let save as the contents of a cell. EPPlus doesn't validate that you have matching brackets, quote marks and so on; so you can put something invalid in as a formula. 

As it stands, export excel only allows simple values to be exported to a cell. So if you have something which needs value and hyperlink to be set then it may need its own custom code to take a sheet object and write to its cells.  Currently we trap two cases. 

```
$newobj = New-Object pscustomobject -Property @{Link= [uri]::new("\\localhost\C`$\Users\mcp") ; stuff = "Text"}
$newobj2 = New-Object pscustomobject -Property @{Link= [uri]::new("C:\Users\mcp") ; stuff = "Text"}

$newobj,$newobj2 | Export-Excel
```
Creates objects where one property is of type URI. We set the hyperlink property to the URI. This works for an http:// path,  the file path with a local drive works, the one with the UNC creates the hyperlink but it won't open 

I tried this 
```
$newobj3 = New-Object pscustomobject -Property @{Link= "\\localhost\C`$\Users\mcp" ; stuff = "=HyperLink(a4,b3)"}

$newobj,$newobj2,$newobj3  | Export-Excel

```

That creates a clickable link. I have no idea why putting the link the =Hyperlink() as literal text does not work but I'd bet on it being a long standing bug in excel around the handling of UNC names. 
But I would export the UNC and Name as text in their own columns and fill in the fomula in the next column, format it to look like a link and hide the others.  It's the best I can do I'm afraid.

**Comment by DarkLite1** [comment]
Thank your for the help James, I think I'm going to follow your advice. I now have the following that works fine:

```powershell
$Test_data = @(
    [PSCustomObject]@{
        ComputerName  = 'PC1'
        SoftwareCount = "=HyperLink(d2,c2)"
        Count         = 5
        Link          = "\\localhost\s$\Test\PC 1.xlsx"
    }
    [PSCustomObject]@{
        ComputerName  = 'PC2'
        SoftwareCount = 0
        Count         = 0
        Link          = $null
    }
    [PSCustomObject]@{
        ComputerName  = 'PC3'
        SoftwareCount = "=HyperLink(d4,c4)"
        Count         = 4
        Link          = "\\localhost\s$\Test\PC 3.xlsx"
    }
)

$Test_data | Export-Excel .\test_share.xlsx
```

I'm not trying to figure out how to color a link blue, and one that doesn't have one not. And how to hide the last 2 columns. Getting there :)

**Comment by DarkLite1** [comment]
This is helpful but it also colors the `0` values that don't have a link and the header.

```powershell
$sheet = $Excel.Workbook.Worksheets | Select-Object -First 1
$sheet.Column(2) | Set-ExcelRange -UnderLine -FontColor Blue
$sheet.Column(3) | Set-ExcelRange -Hidden
$sheet.Column(4) | Set-ExcelRange -Hidden
```

**Comment by DarkLite1** [comment]
Went for this solution instead:


```powershell
$Test_data = @(
    [PSCustomObject]@{
        ComputerName  = 'PC1'
        SoftwareCount = 5
    }
    [PSCustomObject]@{
        ComputerName  = 'PC2'
        SoftwareCount = 0
    }
    [PSCustomObject]@{
        ComputerName  = 'PC3'
        SoftwareCount = 4
    }
)

$MachineFiles = @{
    'PC1' = "\\localhost\s$\Test\PC 1.xlsx"
    'PC3' = "\\localhost\s$\Test\PC 3.xlsx"
}

$Excel = $Test_data | Export-Excel .\test_share.xlsx -PassThru -TableName PC -AutoSize -WorksheetName SCCM

$sheet = $Excel.Workbook.Worksheets | Select-Object -First 1

foreach ($row in (($sheet.Dimension.Start.Row + 1) .. $sheet.Dimension.End.Row)) {
    if ($Link = $MachineFiles.($sheet.Cells[$row, 1].Value)) {
        $Value = $sheet.Cells[$row, 2].Value
        $sheet.cells[$row, 2].Hyperlink = $Link
        $sheet.cells[$row, 2].Value = $Value
        $sheet.cells[$row, 2] | Set-ExcelRange -UnderLine -FontColor Blue
    }
}

Close-ExcelPackage $Excel
```
