### ISSUE TITLE
issues with date as sring 

### ISSUE THREAD

**Issue by joe161314** [dfinke/ImportExcel#553]
hi im having issues with export-excel saving the data as String rather than a date format i hae tried the below...

    Select-Object -Property Name, DateOfBirth, 
        @{Name = 'DateTime'; Expression = {[DateTime]$_.DateOfBirth}} |
    Export-Excel ...

but it only does it for 2 or 3 dates in the list and converts them to us format MM/DD/YYYY i need it to be DD/MM/YYYY

**Comment by pkarunkar** [comment]
It depends on what format you have the date at source. is it Unix, OADate etc etc. 
However your question is not clear, 
Do you want to save the date as string or date as date?

The below ex may help you if you need it as string

`(Get-Date).ToString('dd/MM/yy')`

if the data is coming as string and you want to convert the column into date, then try Set-ExcelColumn

```
$xl = Open-ExcelPackage C:\Users\PavithrasagarK\Desktop\Newfolder\date.xlsx
Set-ExcelColumn -ExcelPackage $xl -Worksheetname 'Sheet1' -Column 1  -NumberFormat 'Short Date' 
Close-ExcelPackage $xl
```

**Comment by joe161314** [comment]
I'm importing the data from a text file for example 
Expireydate
12/01/2019
15/01/2019
30/01/2019
Ect....

I tried set-excelcolumn and it formats the cell into date format but the data in the cell stays as a string until you either select the cell and add a return and it updates or do text to column

**Comment by pkarunkar** [comment]
OK yes, I see the same, Double click the cell and press enter to have Custom Date updated. 
I will step out from discussion now and leave it for other experts to explore why.

**Comment by dfinke** [comment]
# Date is string until it is edited

```powershell
$xlfile = "$env:TEMP\expiration.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$excel = ConvertFrom-Csv @"
Expires,Month,Day,Year
1/12/2019,"=month(Expires)","=day(Expires)","=year(Expires)"
1/15/2019,"=month(Expires)","=day(Expires)","=year(Expires)"
01/30/2019,"=month(Expires)","=day(Expires)","=year(Expires)"
"@ | Export-Excel $xlfile -AutoNameRange -PassThru -AutoSize

Set-Format -WorkSheet $excel.Workbook.Worksheets["Sheet1"] -Range A4 -NumberFormat "dd-MMM"

Close-ExcelPackage $excel -Show
```

@jhoneill, this looks familiar, but it was when the cell needed `[]` because Excel formulas work that way.

**Comment by jhoneill** [comment]
In @dfinke 's example only one country uses "least significant in the middle" dates, so everywhere else those dates will not be recognized as dates :-) 

In Dotnet [datetime]"String". works with most least significant last (Japanese) dates as YYYY-MM-DD  or YYYY/MM/DD. If given 01-02-03 it reads it as a US date. In Japan it means 3rd day of Feb 2001 and in most places it will be 1st day of Feb 2003. 

We don't try to parse dates when exporting because (a) parsing strings for numbers, dates and URIs is slow the less we do the faster it is .
(b) We will be wrong in most of the world. We can say "You must use US format, like .NET and SQL" but that will upset some people (and it's not how Excel itself works), or we can use local format which means a different file means different things on different computers. 
Therefore we take a cop out. If it's a [datetime] object it goes in as an excel date, formatted to use local date-time style. We don't even look for strings which might be dates  that means you have to do what @joe161314 was doing. 
But if you do` [DateTime]$_.DateOfBirth` it _assumes the date is US format_. 
For _local format_ you need to use `[Convert]::ToDateTime($_.DateOfBirth)` 
and if you know the format is _not US and it might not be the local format_ on the computer use `[datetime]::parseExact() `

 The world is unlikely to adopt a single date format and to convert to/from Local/US is always ugly.
Look.
```
>$x = [datetime]::Now
>$x 
28 February 2019 09:43:19
>"$x" 
02/28/2019 09:43:19

>$x.ToString()
28/02/2019 09:43:19

>[string]::Concat("",$x)
02/28/2019 09:43:19

>[string]::Format("{0}",$x )
28/02/2019 09:43:19

```
PowerShell Format XML, implicit to string, explicit to string  all do different things. The string format operator does one thing, and the string concatenate operator does something else.

**Comment by robertcatgithub** [comment]
I'm having this "still string after Set-Format" issue: on csv data in this format "01/05/2022"
Set-Format  ... -NumberFormat 'Short Date' does not work until [ENTER] in the cell

**Comment by jhoneill** [comment]
If you are reading a string from a CSV and not converting it to a date, then when it goes into excel it will still be a string....

**Comment by robertcatgithub** [comment]
> If you are reading a string from a CSV and not converting it to a date, then when it goes into excel it will still be a string....

my code: import-csv $csv | export-excel.....

does the package provide a function to do the conversion between the import & export ?

**Comment by dfinke** [comment]
@robertcatgithub No, you need to handle the string conversions to the data types you want

**Comment by jhoneill** [comment]
PowerShell does it with 
```
import-csv |  select-object  -property *,@{n='PropertyName'; e={[datetime]$_.PropertyName  }} -ExcludeProperty PropertyName
```
If you NOT using least-significant-in-the-middle dates use this instead. 
```
import-csv |  select-object  -property *,@{n='PropertyName'; e={[convert]::todateTime($_.PropertyName) }} -ExcludeProperty PropertyName
```
