### ISSUE TITLE
Selecting Columns in ConvertFromExceltoSQLInsert.ps1

### ISSUE THREAD

**Issue by TerryGriner** [dfinke/ImportExcel#595]
I like what the cmdlet does, I just would like a Parameter that would allow me to select specific Columns from the spreadsheet to import into SQL data table. To use the example to illustrate;
 | File: Movies.xlsx            -           Sheet: Sheet1           |
  ----------------------------------------------------------
 |                A                 B                     C                       |
 |1     Movie Name      Year               Rating                  | 
 |2     The Bodyguard    1992               9                       |
 |3     The Matrix            1999               8                       |
 |4     Skyfall                   2012               9                       |
 |5     The Avengers        2012                                       |
 ----------------------------------------------------------
I want to be able to select column A and B, but not get C on the import.

**Comment by ili101** [comment]
@dfinke It looks like the parameters on `ConvertFrom-ExcelData` and `ConvertFrom-ExcelToSQLInsert` are outdated.
This should do what @TerryGriner want:
``` PowerShell
ConvertFrom-ExcelToSQLInsert -Path Book1.xlsx -TableName Test -HeaderName 'A', 'B'
```
But on `ConvertFrom-ExcelData` and `ConvertFrom-ExcelToSQLInsert` the parameter name is `-Header` instead of `-HeaderName` like in `Import-Excel`.

Maybe it will be best to set DynamicParam on `ConvertFrom-ExcelData` and `ConvertFrom-ExcelToSQLInsert` from `Import-Excel` like @jhoneill did in `Send-SQLDataToExcel` in the last update so it will be updated automatically.

**Comment by ili101** [comment]
Also if you want 'A' and 'C' instead of 'A', 'B' you can't do it with `-HeaderName` but with something like what I proposed in here https://github.com/dfinke/ImportExcel/pull/579 you can select any column you want with `-HeaderName`

**Comment by dfinke** [comment]
Didn't think of using `HeaderName`, was looking at adding `-Property` and use `Select-Object`.

I'll take a look at #579 too.
