### ISSUE TITLE
Import-Excel Error importing data on a file that is open

### ISSUE THREAD

**Issue by benlrivera** [dfinke/ImportExcel#607]
I use to be able to use import-excel even if the file was open but now I am not able to. I receive the following error.

New-Object : Exception calling ".ctor" with "1" argument(s): "The process cannot access the file 'File.xlsx' because it is being used by another process."
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\6.1.0\Open-ExcelPackage.ps1:63 char:35
+ ...  {$pkgobj = New-Object -TypeName OfficeOpenXml.ExcelPackage -Argument ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
 
Close-ExcelPackage : Cannot bind argument to parameter 'ExcelPackage' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\6.1.0\ImportExcel.psm1:417 char:58
+ ...    if ($Path) {Close-ExcelPackage -ExcelPackage $ExcelPackage -NoSave ...
+                                                     ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Close-ExcelPackage], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Close-ExcelPackage
 
Failed importing the Excel workbook 'File.xlsx' with worksheet 'Sheet 1': Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\6.1.0\ImportExcel.psm1:415 char:17
+ ...     catch { throw "Failed importing the Excel workbook '$Path' with w ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed importin...o a null array.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed importing the Excel workbook 'File.xlsx' with worksheet 'New Hires': Cannot index into a null array.

**Comment by dfinke** [comment]
Thanks! Yeah, a change was made to move to opening the Excel Package rather than a file stream.

@jhoneill does `OfficeOpenXml.ExcelPackage` have a read only flag or something similar maybe?

**Comment by jhoneill** [comment]
The change was made quite a long time ago, but in 5.0.0 it went  
```
$Stream = New-Object -TypeName System.IO.FileStream -ArgumentList $Path, 'Open', 'Read', 'ReadWrite'
$Excel = New-Object -TypeName OfficeOpenXml.ExcelPackage -ArgumentList $Stream          `
```

and now it goes 
`$ExcelPackage = Open-ExcelPackage -Path $Path`
and inside open-excelPackage it is the same code whether we open for read or write. 
`New-Object -TypeName OfficeOpenXml.ExcelPackage -ArgumentList $Path`


So I'd do it exactly the way you're describing, read only switch then 
`if ($readonly) {old code} else {current code} 
`

**Comment by DarkLite1** [comment]
Same issue here, quite annoying frankly. Glad you guys figured it out. Another way I had in mind was just making a copy in the temp folder and using that file to read from. But indeed, it might be better to fix it at the source.

**Comment by jhoneill** [comment]
@DarkLite1 , this will probably sound like I'm getting all shirty and it's not meant to. 
This change has been in for some months, and if it's annoying then PLEASE tell us. It could have been Doug who made the change, but I'm pretty sure it was me. Neither of us picked up the issue: we don't promise to fix annoyances like this but we can only fix things we know about. Don't suffer suffer in silence, assuming that something that strikes you as wrong was deliberate. 


@dfinke I got a bunch of problems from the tests adding -readonly to Open-ExcelPackage (it may be a question of a where a stream is opened, and it then closing properly later. ) So I've put the old code back into Import-Excel and all the tests pass - and I can import from a file which is open in excel. All the tests pass so a PR is heading your way.

**Comment by dfinke** [comment]
@jhoneill I've taken a couple tries at this. It's definitely a bit of a whack a mole. Haven't figured out the pattern yet.

**Comment by DarkLite1** [comment]
No worries James, all good here. I only noticed it recently and thought about opening an issue for it. But @benlrivera beat me to the punch, or how do they say these things in the USA? :) 

Thanks for the fix, appreciate it.

**Comment by jhoneill** [comment]
@DarkLite1  all good then . I don't know if they say that in states USA, being English myself :-)

**Comment by DarkLite1** [comment]
> @DarkLite1 all good then . I don't know if they say that in states USA, being English myself :-)

I love the Scotts, but I'll make an exception for you James ;)

**Comment by benlrivera** [comment]
Thank you so much for all the responses and working a solution. Great job!!!

**Comment by canufrank** [comment]
Has this been reverted again? As I encounter the identical error
`New-Object : Exception calling ".ctor" with "4" argument(s): "The process cannot access the file 'C:\Path\File.xlsx' because it is being used by another process."
At ~\Documents\WindowsPowerShell\Modules\ImportExcel\7.1.1\Public\Import-Excel.ps1:110 char:27
+ ...   $stream = New-Object -TypeName System.IO.FileStream -ArgumentList $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
 
Exception calling "Load" with "1" argument(s): "Object reference not set to an instance of an object."
At ~\Documents\WindowsPowerShell\Modules\ImportExcel\7.1.1\Public\Import-Excel.ps1:113 char:24
+                 else { $ExcelPackage.Load($stream) }
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException
 
You cannot call a method on a null-valued expression.
At ~\Documents\WindowsPowerShell\Modules\ImportExcel\7.1.1\Public\Import-Excel.ps1:218 char:30
+                 if ($Path) { $stream.close(); $ExcelPackage.Dispose() ...
+                              ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Failed importing the Excel workbook 'C:\Path\File.xlsx' with worksheet 'vob3': Worksheet 'vob3' not found, the workbook only contains the worksheets ''. If you only wish to select the first worksheet, please remove the '-WorksheetName' parameter.
At ~\Documents\WindowsPowerShell\Modules\ImportExcel\7.1.1\Public\Import-Excel.ps1:216 char:21
+ ...     catch { throw "Failed importing the Excel workbook '$Path' with w ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed importin...ame' parameter.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed importing the Excel workbook 'C:\Path\File.xlsx' with worksheet 'vob3': Worksheet 'vob3' not found, the workbook only contains the worksheets ''. If you only wish to select the first worksheet, please remove the '-Wor 
   ksheetName' parameter`

**Comment by dfinke** [comment]
@canufrank, please open this in a new issue, and post a simple repro
