### ISSUE TITLE
Unable to find type [OfficeOpenXml.ExcelPackage]

### ISSUE THREAD

**Issue by jpfieber** [dfinke/ImportExcel#616]
Running as a normal user in PowerShell ISE or as an elevated administrator.

Installed ImportExcel 6.2.0 using `Install-Module -Name ImportExcel -Scope CurrentUser` .

Using Powershell 5.1 (18362.145)

If I run the following script:
```
Install-Module -Name ImportExcel -Scope CurrentUser
get-service | export-excel
```
I get the following error:
```
Unable to find type [OfficeOpenXml.ExcelPackage].
At line:435 char:17
+     [OutputType([OfficeOpenXml.ExcelPackage])]
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (OfficeOpenXml.ExcelPackage:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```
Note: I tried installing the module for all users and running PowerShell as administrator and the `get-service | export-excel` command does work that way. 

I'm trying to get NTFS permissions from a network share and write them to an Excel report, so I need to run the script as a user with privileges to the share (elevated won't work), which is why I'm using the recommended "CurrentUser" method, which doesn't seem to work for either the regular user or the elevated user.

**Comment by jhoneill** [comment]
_Can't find the type_ suggests that the dll didn't get loaded when you imported the module. 
Can you do 
Import-Module importExcel 
and look for any errors and then 
get-service | export-excel

If that fails try running this 
`Add-type -path "$env:userProfile\Documents\WindowsPowerShell\Modules\Importexcel\epplus.dll"
`
(it will throw an error if the DLL isn't there) if you type `[OfficeOpen  ` [tab] it should tab compete officeOpenXML 

One other thing you could try for us. We have lots of 6.0.0 installs and no-one has reported this problem you could install with -version 6.0.0 and see if that works, because that would indicate a problem packaging 6.2 for download.  I'm running the 6.2 code from a folder under my user directory and that's OK on both 5.1 and 6.2, and I think all the automated tests install for the current user (the testing account doesn't have privileges to install for all).

**Comment by jpfieber** [comment]
Duh, my bad. Doing `Import-Module` in the script instead of `Install-Module` made all the difference. Working now. Thanks!
