### ISSUE TITLE
Import-excel null array error on XLS

### ISSUE THREAD

**Issue by hobbex** [dfinke/ImportExcel#617]
Hi, 
I'm new to Import-Excel.
When i try to open a  xls file, import-excel gives me this error:

```
Failed importing the Excel workbook '' with worksheet '': Failed creating property names: Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\ImportExcel\6.2.0\ImportExcel.psm1:418 char:17
+ ...     catch { throw "Failed importing the Excel workbook '$Path' with w ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed importin...o a null array.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed importing the Excel workbook '' with worksheet '': Failed creating property names: C 
   annot index into a null array.
```

However, if i open the xls file in Excel and save it as XLSX, it works like a charm.
Is this a bug?

How can i use xls-files?

**Comment by dfinke** [comment]
XLS files are not supported. There is `ConvertTo-ExcelXlsx`, but it requires Excel to be installed.

**Comment by hobbex** [comment]
Thanks for quick answer!
Too bad xls is not supported. 


Strangley enough i didn't find any info regarding this after several Google searches. 

Unfortunately converttoxlsx is not working for me, since I'm using this on a server where i don't want to install excel. 
This also part of an automated process, so i cannot convert the xls manually iether . 

Any other ideas?

**Comment by jhoneill** [comment]
First of all if you still have something which generates XLS files it really should be updated. XLSX has been current for more than a decade now. Processing those files tends to be seen as solved problem, so there isn't much development being done on XLS. Import-Excel wraps another project named EPPlus, and doesn't make much effort to say "this is XLSX only" and the failure is not graceful.  There's a similar like of grace about the failure in our module. 
When I had to solve the problem of not putting excel on servers, combined with some ancient software which exported XLS,  the best I could do was get the access runtime from https://www.microsoft.com/en-gb/download/details.aspx?id=10910 
what you can then do is open an XLS as a database and each sheet and each named range behaves as a table, so you can use ODBC to connect to it. 
If you get my module GetSql from the PowerShell gallery that's an easy wrapper for it 
You can do 
`get-sql -excel -connection <<filename>> -table <<name>> -close   `
Or 
```
get-sql -excel -connection <<filename>> 
$One = get-sql -table <<name 1>>
$Two = get-sql -table <<name 2>> 
get-sql -close

```
It's not as flexible as import excel  - if the first row of a sheet is not a list of column headings you probably won't get a valid table, and if the data in a column is a mixture of types it will probably be treated as a text by ODBC. I use it to update an excel database of Formula one race results - because the script which screen scrapes them is old than epplus and import excel - so "Place" has 1,2,3 but also "retired", "disqualified" etc. so that column is text and Excel then tells me "You've got a text cell with a number in - do you want to change it ?". If I read with ODBC place is text field so I can't say "select the rows for this driver and calculate the average" etc.

**Comment by hobbex** [comment]
Unfortunately it's impossible to update the source program that generates the xls-file. It's a economy application.

Your ODBC solution with get-sql is good enough in this situation.

Thanks alot for the answers and the the suggestions.

**Comment by jhoneill** [comment]
:-) If I had a small amount of money for each time I'd hear "We can't update X" I could retire.  Customers who say X depends something else which is out of support or X itself has ceased to be supported, yet X is also business critical. 
I had to use the ODBC solution for a client who had an app which dates from the 1990s, and the vendor put XLS support in then and told us that as long as Excel could read XLS they would keep writing it so I share the pain.
