### ISSUE TITLE
Import all data as Text

### ISSUE THREAD

**Issue by eilandnl** [dfinke/ImportExcel#645]
Is it possible to make a optional setting to import all as text 
Now i have manually changed this:
$NewRow[$P.Value] = $Worksheet.Cells[$R, $P.Column].Value
to this: 
$NewRow[$P.Value] = [string]$Worksheet.Cells[$R, $P.Column].Value

**Comment by jhoneill** [comment]
There is a block from line 414 which goes

```
            else {
                #region Create one object per row
                foreach ($R in $Rows) {
                    $NewRow = [Ordered]@{ }

                    foreach ($P in $PropertyNames) {
                        $NewRow[$P.Value] = $Worksheet.Cells[$R, $P.Column].Value
                    }
                    [PSCustomObject]$NewRow
                }
                #endregion
            }

```
you could insert before it 
```
            elseIf ($AsText) {
            }
```
with identical code except 
`                        $NewRow[$P.Value] = $Worksheet.Cells[$R, $P.Column].Text`
(ending in TEXT rather than value), 

This would avoid having to cast every cell to a string and would also avoid an IF on every cell.
