### ISSUE TITLE
Working Example for Set-WorksheetProtection?!

### ISSUE THREAD

**Issue by peschu123** [dfinke/ImportExcel#653]
Hi,
I tried hard, but I cannot get the "Set-WorksheetProtection" Function to work with my PowerShell script. Could someone provide a very simple example to point me in the right direction?

Further I found a line in the Set-WorkSheetProtection.ps1 which is not clear to me. Should the variable not be "$lockAddress" (instead of $unlockaddress)?

https://github.com/dfinke/ImportExcel/blob/b82888527f05b122449c7dc291c28adc65181a07/Set-WorkSheetProtection.ps1#L79

Thanks and KR,

Peter

**Comment by jhoneill** [comment]
I think you are correct , that line is an error. Particularly if you look at if statement on the previous line ... 

Actually set-WorksheetFunction.ps1 is included in the code but it is not exported by the PSD1 file, I think because it wasn't properly finished - it doesn't have any tests for a start. 
I'll have a proper look at at it this weekend because I think it is one of mine.  As well as not locking cells it is told to as reported, It should probably lock all cells unless told otherwise

**Comment by peschu123** [comment]
Thank your for the quick reply.
At least I found a way to add the protection to my Excelsheet like this:

```
$excel = Open-ExcelPackage $xlsx_file
$sheet = $excel.Workbook.Worksheets["Budget"]
$sheet.Protection.IsProtected  = $true
Set-ExcelRange     -Range $sheet.cells["H:I"] -Locked:$false
Set-ExcelRange     -Range $sheet.cells["I7"] -Locked
$sheet.Protection.SetPassword("test")
Close-ExcelPackage $excel`
#I have code before, where $xlsx_file is loaded...it's the path to a xlsx file ;)
```


I use powershell for the second day now, so the above code is probably not best practice, but I needed a (temporary) solution. And this seems to work, after short testing.

Per default nothing is locked.

**Comment by dfinke** [comment]
Looks like good code for only two days using PowerShell

**Comment by rvanherk** [comment]
@peschu123 Do you know a way to undo the Sheet protection when you would open the protected file again with Powershell?
