### ISSUE TITLE
Columns created as a formula don't autosize

### ISSUE THREAD

**Issue by wgshef** [dfinke/ImportExcel#672]
Using Set-ExcelRange to make a column a formula. Subsequently, the column cannot be autosized.
I've tried with the -AutoSize paramater to Set-ExcelRange, and also:
$Sheet.Column(15) | Set-ExcelRange -AutoSize;

**Comment by uSlackr** [comment]
In my experience, formulas set via Importexcel do not calculate until the workbook is opened interactively.  This implies autosize will not have data to work on until its been  opened and saved interactively.

You  can set columnwidth which has worked well for me since I know what final results  will look like.



\\Greg

________________________________

**Comment by jhoneill** [comment]
Basically it's as @uSlackr  says the formula isn't evaluated until the file is opened in excel

You can do
`[OfficeOpenXml.CalculationExtension]::Calculate($Sheet) `
before trying to autosize, but the EpPlus module doesn't calculate everything.
