### ISSUE TITLE
Pivot tables questions

### ISSUE THREAD

**Issue by scriptingstudio** [dfinke/ImportExcel#700]
1. PivotFilter takes entire column. In Excel app I can filter the column by value.
How to do that via Add-PivotTable? New feature to pull request?

2. Some values of PivotRows can be empty. Is it possible to give them name?

see image attached. Some titles in russian.

![image](https://user-images.githubusercontent.com/17237559/67558932-9ad25300-f720-11e9-9d93-374f3783e630.png)

**Comment by jhoneill** [comment]
No, sadly.
 The file doesn't know what is in the pivot table until Excel has processed it. We've looked for a work-round because being able to apply the filter has been requested more than once, and it's something I wanted, but no luck.
I don't think excel has a way of naming the row in the pivot table for empty cells.
