### ISSUE TITLE
Get-ExcelTable object creation optimization

### ISSUE THREAD

**Issue by scriptingstudio** [dfinke/ImportExcel#702]
I removed extra hashtable expansion and object conversion

   
```
    for($row=$startRow; $row -lt ($startRow+$rowCount); $row++) {
        $nr = '' | select-object $propertyNames
        $c = 0
        for($col=$startCol; $col -lt ($startCol+$colCount); $col++) {
            $nr.($propertyNames[$c++]) = $Worksheet.Cells[$row, $col].value
        }
        $nr
    }
```

**Comment by dfinke** [comment]
Ok. Not sure where this goes or which it replaces. Please consider forking the repo, changing the code and doing a pull request.

**Comment by jhoneill** [comment]
This looks like a speed up for the central part of import-excel, but it won't work with `-DataOnly` it does all rows and columns.  Since that is only used rarely , we could have an IF which does the current thing if dataonly is specified and uses this for speed if not. I don't have any feel for how much faster it would be ...
A friend of mine named Jonathan Noble introduced me to the trick of creating an object with a custom set of properties by doing `"" | select-object -prop name1,name2,name3 ` so I came to know it as "**the Noble method**" , which is what is being done here rather than build a hash table and cast it to [pscustomobject]. It's efficient, but I've come to regard it as bad style. 
I
've also made a change to this area in my latest commit to support -asText, a PR for that will be arriving shortly.
