### ISSUE TITLE
AutoSize adds way too much padding / empty space

### ISSUE THREAD

**Issue by o-l-a-v** [dfinke/ImportExcel#707]
I'm on latest and greates ImportExcel, PowerShell 5.1 on Windows 10 1909.

Export-Excel with "AutoSize" enabled is great. Only caveat/ problem is that it adds way too much padding/ empty space sometimes. Here's are some examples, the screenshots shows the longest word in given column. 

(This is probably hard to calculate, but I'm still hoping it's possible to make improvements to this functionality. :) )

![image](https://user-images.githubusercontent.com/6450056/68013838-471ab900-fc8e-11e9-8269-d50acb358133.png)

![image](https://user-images.githubusercontent.com/6450056/68013871-57cb2f00-fc8e-11e9-8652-abd914d00122.png)

Command used
```powershell
$SomeObject | Select-Object -Property 'some','properties' | Export-Excel -Path 'somewhere\file.xlsx' -Autosize -TableStyle 'Medium2' -TableName 'SomeName' -WorksheetName 'SomeName' -Title 'SomeTitle'

**Comment by jhoneill** [comment]
This is a limitation on the Autosize function in the EPPlus library we use. It uses a .DOT function to calculate the width of the text and its not especially reliable. The most common problem is "Standard" dates being different formats in different countries so leading zeroes may or may not be present.  The one you've presented is odd because most of the case I've seen it allocates too little space rather than too much. 
We can work on the EPPlus folks, but nothing much we can in the PowerShell code I'm afraid.

**Comment by uSlackr** [comment]
Are the column headers included in the sizing effort?  I assume so.  Which still leaves extra space in the example, but not as much.


\\Greg

________________________________
