### ISSUE TITLE
Import-Excel // Dates with formatting are imported as numbers

### ISSUE THREAD

**Issue by AlexBillon07** [dfinke/ImportExcel#754]
Powershell 5.1
ImportExcel 6.5.2

Hello,

Dates are imported as numbers when they are formatted in Excel Files.
I am not sure if this is a bug or not.

I have read the issue https://github.com/dfinke/ImportExcel/issues/289 and learned about the `DateTime.FromOADate(Double)` method. So I have a workaround but it would be nice to import formatted dates as dates with the Import-Excel cmdlet.

[Test.xlsx](https://github.com/dfinke/ImportExcel/files/3960584/Test.xlsx)

```
PS C:\Temp> Import-Excel .\Test.xlsx -WorksheetName 'WithoutFormatting'

Number Text Dates
------ ---- -----
     1 azae 13/12/2019 00:00:00
     2 fdz  14/12/2019 00:00:00
     3 1    15/12/2019 00:00:00
     4 azd  16/12/2019 00:00:00
     5      17/12/2019 00:00:00
     6
     7


PS C:\Temp> Import-Excel .\Test.xlsx -WorksheetName 'Formatted'

Number Text Dates
------ ---- -----
     1 azae 43812
     2 fdz  43813
     3 1    43814
     4 azd  43815
     5      43816
     6
     7

```

Best Regards,

Alex

**Comment by jhoneill** [comment]
It is a known problem. 
Excel doesn't have dates. It just has numbers as days since 1 Jan 1900 converted to date and time. 
The EPPlus library recognizes dates if the cell uses one of the built in date formats (each format used in the sheet has an ID. Low numbers are assigned to built in formats and user formats get a higher number. Dates are 14,15,16,17). EPPlus doesn't look to see if the format is a combination of letters, numbers and separators which would make a date format, and you can imagine how slow that would be if we tried to do it for each cell. 
There are two options  one is to use FromOADate() 
The other is to import with   -AsText "Dates" (or whatever your column name is) this will preserve the text formatting which may be what you want; but if you want proper dateTime object from a  custom formatted column the FromOADate method is the best way.

**Comment by AlexBillon07** [comment]
Yeah, I thought so. But I wanted to be sure.
Thanks.
