### ISSUE TITLE
[Question] Process multipe excels with diffrent start rows

### ISSUE THREAD

**Issue by cprograemer84** [dfinke/ImportExcel#779]
Hello group,

First of all many thanks to @dfinke  and @jhoneill  for the wonderful module. I have used this module and the results are amazing, I am great full for all their and the community.  
 am a functional consultant and not a programmer by profession so end up some basic queries one of which is given below, appreciate if you can look into and advise.

My existing solution works on standard format of excel they read excel and do validations on the data based on defined rules and color code the cells.

A new challenge that I have come across is , I am receiving excel sheets that are deviating from the standard format and do not  start at the same fixed row (As dictated by the fixed format of the template to start at row 10 with the first 9 rows has headers, logo etc). 
The data either start 1 or two rows before of 1 or two rows after the standard format.
So e.g. some spreadsheets start at row 8, 9 or 11 12.

Question: How do i read the excel and dynamically calculate the correct start row and truncate the rows above the actual start row. in memory,  the actual start row begins with  the words "MODEL ID" and above and below are some other instructions text and header information which is not required for processing.  I get the users to dump all excels in one folder and then loop through all excel one by one and perform data validation on the excels. 

Thanks in advance. 

Regards,
RJ

**Comment by naterrey** [comment]
So I am going to give this a go, but first a few clarifying questions:
1. Are you putting into multiple sheets like in AddMultiWorksheet example or are you multiple tables in one sheet like in the Multiple tables example?
[MultiTWorksheet](https://www.powershellgallery.com/packages/ImportExcel/7.0.1/Content/Examples%5CAddWorkSheet%5CAddMultiWorkSheet.ps1)
[MultiTable](https://www.powershellgallery.com/packages/ImportExcel/7.0.1/Content/Examples%5CTables%5CMultipleTables.ps1)

2. From what I am gathering you are trying to bring multiple excel documents in a specified folder (Quantity Unknown) into 1 whether it be in multiple sheets or consolidate them into one table or mutliple tables on 1 sheet, are you using -dataonly property?

If you are not using -dataonly property, I might suggest doing that then place the data in a Powershell object table, remove all items before "Model ID", and then if you still want the graphics and other data in there append them back in the sheet via powershell.
The other option that I may suggest instead is to get the value in A:10 and if it doesn't equal "Model ID" send the creator an email that explains the document cannot be process because it does not match the required format... because if they realize they don't have to push it to the folder in any specific format they will veer further and further away and you may have to keep updating the script with more and more manual logic (give them an inch they take a mile)
