### ISSUE TITLE
Is there a function or mechanism to do intermediate processing between SQL and Export-Excel?

### ISSUE THREAD

**Issue by dtrue** [dfinke/ImportExcel#781]
Is there a way to intercept the query data returned from MS SQL server prior to creating Excel/Table output?
So like...use a Send-SQLDataToExcel  type equivalent but allow processing on the exported data prior to dumping into Excel worksheet.  Basically allow the ability to do conditional checks/tests on the data which may change the dataset actually imported into excel....or even allow the data to drive potentially creating different excel files/worksheets etc.  
Simple usecase would be retrieve data from MS SQL....if the state value in the row is California...generate a certain workbook/worksheet/format.  If some other state....generate a different format.

**Comment by dfinke** [comment]
There's no mechanism to process the data before it hits Excel. @jhoneill wanted to double check with you.

**Comment by jhoneill** [comment]
Yes and no. You can do a SQL query, do whatever you want to results that are returned and send the output to Excel. 
I have a "GetSql" module on the [powershell gallery](https://www.powershellgallery.com/packages?q=getsql) (and on here) , and Send-SQLDataToExcel is cannibalized from that, so you can do 
Get-Sql @params | update-stuff | export-excel. 
I figured that the requirement was either 
Here's my SQL, run it _there_ and send it to _this excel file_ with _these_ options 
or 
_I'll get my own data and process it,_ thanks, but send it to excel for me. So Export-Excel will allow you to hand it a datatable rather than a bunch of data rows.

**Comment by dtrue** [comment]
Thanks! And great module!!
