### ISSUE TITLE
Appending data to next open row and skipping one row

### ISSUE THREAD

**Issue by xkdc** [dfinke/ImportExcel#813]
Is there a way to export data to an existing excel sheet but have it append to the next empty row,  skipping one line for space? I know there is -append but that seems to only add data to the current data and also doesn't add headers.

If possible I would like to append the data to the next empty row, be able to skip one line for spacing and also include the headers. If this is also possible for the pivot tables too, that would be fantastic. 

Thanks!

**Comment by dfinke** [comment]
Sounds interesting. Could you post an example of sorts?

**Comment by xkdc** [comment]
Sure thing - here's what I would ultimately like for it too look like. As you know, -append would only add the data to the last row. Instead of adding to the data, I'm trying to export a snapshot in time so I need them to be separate instances hence the headers being included, plus separate pivot tables for each. Something like that would great. -Thanks

![1](https://user-images.githubusercontent.com/35116884/79025179-03887d00-7b53-11ea-8b0d-0813194fe99b.PNG)
![2](https://user-images.githubusercontent.com/35116884/79025192-084d3100-7b53-11ea-842f-6d4a93de1fa2.PNG)

**Comment by dfinke** [comment]
I like the idea, seems to custom tho, and better handled from and en users perspective. Seems like a switch that would add data to a "specific" location and then create a pivot table to a specific sheet/location. Doesn't seem generalizable, but maybe.

**Comment by jhoneill** [comment]
Append is for the same data continuing. If you want headings, and a new table, then you need to use start-row. You can get the dimensions of the existing sheet in a number of ways (using export with `-passthru` if you are doing all the operations at once, or `open-excelPackage` if not) 
You can always do "Start at last current row + 2" 

If you do export with `-passthru` you can use `Add-PivotTable` and specify the exact address of where you want the pivot to go.  This is a little bit more difficult because we don't know the what cells that will used for the last pivot until Excel draws it - there will be a problem if new pivot  overlaps with it. You can find that out from the data,  `$data | group username -no ).count` will be the rows of data, add 1 for the header and whatever safety margin you want.  However if you are adding new data each week it is more difficult. 
If you have 
`$ep = open-excelPackage <<path>>`
`($ep.<<SHEETNAME>>.PivotTables.address.start  | measure -maximum row).maximu`m
will tell you where the last pivot **starts**.  You only know where it ends if the file has been opened in Excel and saved. 
then you can use 
`($ep.Sheet1.PivotTables.address.end  | measure -maximum row).maximum  ` 

In the examples there is pivottable folder, with a multiple pivottables example you can probably find a lot of what you need there.
