### ISSUE TITLE
Working with Hours

### ISSUE THREAD

**Issue by asciiota** [dfinke/ImportExcel#839]
Hi 

Fantastic tool you have created, I am actually enjoying learning how to use it as I see it will be very useful to me.

I am not sure I would call this an issue but I am looking for a way to reproduce Excel behavior in the way it treats hours when using Export-Excel

In Excel when you enter 16:00 it automatically knows its a time and automatically applies a time format to it.  If you then apply a date format to it Excel shows it as Saturday 0 January 1900.

When I import an hour string from a csv file and then use Export-Excel to put that in a spreadsheet it comes through as a string and Excel applies the General format to it.  If you manually apply a date or time format nothing happens because it treats it as a string.

If I use the following

If (Test-Path "C:\Temp\Result.xlsx" -PathType Leaf){Remove-Item -Path "C:\Temp\Result.xlsx" -ErrorAction Ignore}
$data = ConvertFrom-Csv @"
Time
01:00:00.000
"@| Select @{Name='Time';Expression={[datetime]::ParseExact($($_.Time),'H:mm:ss.fff',$null)}}
$data | Export-Excel -AutoSize -Path C:\Temp\Result.xlsx -Show

The result comes through in Excel with today's date with the correct hour.  It does not come through as Saturday 0 January 1900.  I have tried adding the 0/0/1900 to that function but it does not work as its not a valid date.

Is there some way to reproduce Excel's behavior when entering hours into a cell using Export-Excel?

Thanks for the help

**Comment by dfinke** [comment]
## Off the top of my head

```powershell
$xlfile = "$env:TEMP\test.xlsx"
rm $xlfile -ErrorAction SilentlyContinue

$data = ConvertFrom-Csv @"
Time
16:00
17:00
12:00
"@ 

$data | foreach { $_.Time=[datetime]$_.Time}

$xl = Export-Excel -InputObject $data -Path $xlfile -PassThru 

Set-Format -Worksheet $xl.Sheet1 -Range "A:A" -NumberFormat 'hh:mm'

Close-ExcelPackage $xl -Show
```

![image](https://user-images.githubusercontent.com/67258/81489081-80387500-923f-11ea-8776-4e6a576fd19f.png)

**Comment by asciiota** [comment]
Hi Doug

Thanks for the fast response on this.  Your own screenshot actually indicates the same issue I mentioned above.  It includes the date you ran the code even though you did not enter one.

If you enter 18:00 into an Excel cell manually you do not get that.
![image](https://user-images.githubusercontent.com/48511146/81495544-204dd700-92f0-11ea-86a0-f885b878eda0.png)
Is it possible to replicate that behavior with Export-Excel?
Thanks

**Comment by dfinke** [comment]
Got, it. NO, don't know how to strip the date and still retain that it's a date format for Excel to work with.

**Comment by scriptingstudio** [comment]
@dfinke 
```
[datetime]'16:00'
10 мая 2020 г. 16:00:00

([datetime]'16:00').tostring('HH:mm')
16:00
```

**Comment by dfinke** [comment]
@scriptingstudio yeah, tried that, but the desired output in Excel, I believe, is the 16:00 shows, and Excel can manipulate it as a datetime.

**Comment by jhoneill** [comment]
1. Excel doesn't have datetime as a type. It's just a floating point number, with formatting applied, which is why you can add and subtract without saying "Add Days" (or add seconds or whatever) as you would with a date time type. Excel has special handling for fields between 0 and 1 which are formatted as a time, (they are shown only as the time part with the date hidden) and if you force the date part to show it is the 0th of January 1900. Excel, like lotus 123 (and possibly visicalc), can't do dates before 1900.

2. .NET [DateTime] has a date (there's a clue in the name). If it tried to a date of Zero that would be to early for Excel and bad stuff would result. Converting a time to a date time has to choose a day, and it choose the current day. (When we say "6 PM" without saying which day we mean 6PM today so that makes sense)

3. For a time without a day - either the gap between two times, (especially when one was the previous midnight)  .NET has a [TimeSpan] type. We don't do anything special with timespans except format them and they go into a sheet and EPPLus and Excel handle them just fine. 

4. So either create the thing you want as a time as a [timespan] . You can use $MyDateTime.TimeOfDay or [TimeSpan]::parseExact.

**Comment by asciiota** [comment]
Thanks for the answers provided.  It seems that Excel has its own way of treating a manual time only entry.  Thanks for the information and time spent.
