### ISSUE TITLE
Order in -PivotData not maintained ... revisited

### ISSUE THREAD

**Issue by asciiota** [dfinke/ImportExcel#854]
Hi

I have run into the same issue as reported in #158 

It does not matter what order I place the items in the -PivotData list they always come out wrong and as a result the Pivot table is constructed incorrectly.

I have attached the code and sample data that demonstrates the issue.

I am using the Add-PivotTable method and it is at the end of the code.  
You may need to fix the path statement on the first line of code in order to read in the data.

I have tried [ordered] on the list but this generates an error in Powershell.

[Shared.zip](https://github.com/dfinke/ImportExcel/files/4659959/Shared.zip)

Hoping you can help.

**Comment by jhoneill** [comment]
I will try to look at this in the next day or two; because the list is a hash table it will produce an unpredictable order which [ordered] should fix. If [Ordered] is causing problems, hopefully it is something easy to fix.

**Comment by globeinthesky** [comment]
Hello, it's my first post here. I found that passing by parameters works with the [ordered] before the list, directly it gives an error.
try this (I put the -PivotDataToColumn outside because I was not sure how to pass the value)
`$pivotTableParams = @{
Address = $avgWorksheet.Cells["A3"] `
SourceWorkSheet = $dataWorksheet `
SourceRange = $pivotTableRange `
PivotTableName = "AvgingTable" `
PivotNumberFormat = "#,##0" `
PivotRows = "Hour" `
PivotData = [ordered]@{Gate1="Average";Gate2="Average";Total="Average"} `
}
Add-PivotTable @pivotTableParams -PivotDataToColumn -Activate`

**Comment by jpvolkman** [comment]
You can ensure their order by adding them one at a time after the PassThru.

$Field1Count = $Pt1.DataFields.Add($Pt1.Fields["BLAH"])
$Field1Count.Function = 'Sum'
$Field1Count.Format = "#,##0_);(#,##0)"
$Field1.Name = "BLAH"
