### ISSUE TITLE
How can I test, that a cell is formatted as striked through?

### ISSUE THREAD

**Issue by HaraldGewehr** [dfinke/ImportExcel#878]
On Excel cells, I find the parameter StyleID, this value changes strangly, when I change the format of the cell, but I see no schema.

I have to find out, if a cell is striked through (~~striked through~~).

Is there away? I can't figure it out.

(Hope this is a good way to ask this question, it's the first thing I do on Github). Thank you.

**Comment by Spiker985** [comment]
There is a property for all the text formatting options on each cell.

In [this](https://github.com/dfinke/ImportExcel/files/4827815/Non.vs.Strike.xlsx) sample xlsx:
- Cell A1 has text "Non" with no additional changes.
- Cell B1 has text "Strike" with strikethrough set on the cell format

If you open the file with PowerShell through the following snippet:
`$excel = Open-ExcelPackage -Path "<path>\Strike vs Non.xlsx"`

And then access the cells font attributes:
`$excel.Sheet1.Cells["A1"].Style.Font`
`$excel.Sheet1.Cells["B1"].Style.Font`

You can see the following properties:
- Name
- Size
- Family
- Color
- Scheme
- Bold
- Italic
- Strike
- Underline
- Underline Type
- VerticalAlign

I tend to set the property on the cell, rather than use the Set-ExcelRange cmdlet, but to each their own.

**Comment by dfinke** [comment]
@HaraldGewehr perfect place to ask questions.

I have not tried to check if a property is set,  the above approach is where I'd start. Also, you need to use `Close-ExcelPackage -ExcelPackage $excel` at the end of the script to close the  file.

**Comment by HaraldGewehr** [comment]
Perfect. Thanks to you two!

$excel.Sheet1.Cells["A1"].Style.Font works perfectly for me.
