### ISSUE TITLE
Excel dates when opening in Mac Osx

### ISSUE THREAD

**Issue by dtrue** [dfinke/ImportExcel#903]
I used the following NumberFormat property for date formatting in my worksheets                     
Example: Set-Format -Worksheet $ws -Range "Due_Date" -NumberFormat "m/dd/yyyy"
I'm running on Powershell7 on Windows. When this worksheet is opened on a Mac, the date is wrong by about 4 years into the future. Any ideas?

**Comment by dfinke** [comment]
Sorry, I don't have a Mac. The module is tested in general terms for PS and Core on Windows, Linux, and Mac. Can you run the script on Windows? If it has the same error, please post a repro.

**Comment by dtrue** [comment]
Hmm - it looks like this is the setting that needs to be set (vb equivalent).  ActiveWorkbook.Date1904 = false will then make the workbook open up in mac with the appropriate dates. Any way to set the equivalent in your library?

**Comment by dfinke** [comment]
The module functions don't explicitly have that. You can try using `-PassThru` on Export-Excel and then inspect the properties and methods on the object returned to see if there is a settable property.

**Comment by dtrue** [comment]
Thanks!  There is a settable property Workbook.Date1904  Interestingly though if you set it to $true the expected behavior occurs.  If you set it to $false it doesn't work (It looks by default its already set to $false but I specifically set it to $false just to make sure...and it still doesn't impact it!).  I'll see if there is something in the open office xml or wherever that may allow something different.

**Comment by dfinke** [comment]
Thanks for the updates

**Comment by nlsdg** [comment]
This is an attribute stored in the .\xl\workbook.xml file.
The default (on my Windows 10, Office 365) is absent. Setting ThisWorkbook.Date1904 to true adds the date1904 attribute to the workbookPr element.
<workbookPr date1904="1" codeName="ThisWorkbook" defaultThemeVersion="166925"/>

The reason for the setting is explained here: https://docs.microsoft.com/en-us/office/troubleshoot/excel/1900-and-1904-date-system
"Because of the design of early Macintosh computers, dates before January 1, 1904, were not supported. This design was intended to prevent problems related to the fact that 1900 was not a leap year. In the past, Excel for Macintosh defaulted to using the 1904 date system for workbooks originating on a Macintosh. However, Excel for Macintosh now defaults to the 1900 date system and supports dates as early as January 1, 1900."

In  this article (https://support.microsoft.com/en-us/office/date-systems-in-excel-e7fe7167-48a9-4b96-bb53-5612a800b487) it states "Excel 2008 for Mac and earlier Excel for Mac versions calculate dates based on the 1904 date system. Excel 2016 for Mac and Excel for Mac 2011 use the 1900 date system, which guarantees date compatibility with Excel for Windows."
