### ISSUE TITLE
yyyy-MM-dd formatted cells do not return DateTime objects

### ISSUE THREAD

**Issue by robinmalik** [dfinke/ImportExcel#97]
If a date (e.g. 2016-04-22) is entered into a cell without formatting, Excel detects this as a date and automatically sets the cell formatting to the default, top option which displays as: "*14/03/2012". The cell therefore displays 22/04/2016.

When importing the spreadsheet with ImportExcel this is correctly interpreted as a DateTime object (.gettype() returns Name = DateTime, Basetype = System.Value), so we see: 22/04/2016 00:00:00.

However if I modify the formatting of the cell to use a different date format, e.g. 2012-03-14 (yyyy-MM-dd), ImportExcel returns a number like: 42482.

Interestingly, in Excel if I enter a date into a new unformatted cell, let Excel do it's auto set to date format, and then change the formatting on the cell to 'Text' it returns 42482. It looks as though if a cell has the date format dd/MM/yyyy, ImportExcel is able to parse it correctly, but if it's yyyy-MM-dd (and maybe other formats?) it performs some conversion I don't quite understand.

**Comment by dfinke** [comment]
Thanks for the write up. Will investigate.

**Comment by robinmalik** [comment]
Example:

Name|yyyy-MM-ddFormatting|DefaultDateFormatting
-------|-----------------------------|-----------------------------
vmblahblah01|42483|23/04/2016 00:00:00
vmblahblah02|42484|24/04/2016 00:00:00

**Comment by jeffrey-yao** [comment]
Yes, I have exactly the same issue as robinmalik. To repeat the issue, you can create an xlsx just with one column. Yu can initially put a value, like '2016-05-16', then you format the cell to customized format like 'yyyy/mm/dd hh:mm:ss', and save the file. Then you use import-excel -path <file>, and then you will see, you cannot get '2016-05-16', but just a decimal xxxxx.yyyy.

**Comment by dfinke** [comment]
You'll need to do the date conversions on the data after the `Import-Excel` with this 
`[datetime]::FromOADate(42483)` which should return `Saturday, April 23, 2016 12:00:00 AM`

**Comment by jeffrey-yao** [comment]
Thanks a lot, will try and update u tomorrow!

**Comment by jeffrey-yao** [comment]
@dfinke, using [datetime]::FromOADate(<value>) indeed solves the problem, but in my environment, I need to automate multiple Excel file data extraction process, so from automation perspective, I cannot tell which column is a date type column, as I have both date and money type columns in a same Excel spreadsheet. It seems difficult to solve this issue. 
I, however, find that changing one line of your code helps me

     $h.$Name = $worksheet.Cells[$Row,($Column+1)].Value

changing to

    $h.$Name = $worksheet.Cells[$Row,($Column+1)].Text

Do you have any concerns regarding changing .Value to .Text as I have not done extensive tests to see what potential pitfall this will bring? But bottom line is this solves my problem in my environment. Maybe we can add a switch parameter to Import-Excel so that with the switch parameter, we will use .Text, otherwise, by default, it will use .Value ?

Again, thank you very much for your work which I believe benefits the community a LOT.

**Comment by dfinke** [comment]
Thanks for tracking that down. Yeah I have concerns about that. Let me investigate. Maybe adding a switch to the `Import-Excel` return either text  or value might be better. 

The reason why I suggested the workaround is because I could not find a way to determine the datatype from the Excel sheet.
